import { NextRequest, NextResponse } from 'next/server';

const schemes = [
  {
    id: '1',
    name: 'Ayushman Bharat - PM-JAY',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Health Insurance',
    coverage: '₹5,00,000 per family per year',
    benefit: 'Cashless hospitalization coverage up to ₹5 lakh per family per year',
    eligibility: 'Beneficiaries identified by SECC database. Over 10.74 crore poor and vulnerable families covered.',
    documents: ['Aadhaar Card', 'Ration Card', 'Voter ID', 'SECC Document'],
    applyUrl: 'https://pmjay.gov.in/',
    premium: 'Free (Government Funded)',
    coverageAmount: '₹5,00,000',
    familiesCovered: '100+ million families',
    priority: 'ayushman',
  },
  {
    id: '2',
    name: 'Central Government Health Scheme (CGHS)',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Health Insurance',
    coverage: 'Comprehensive out-patient and in-patient',
    benefit: 'Comprehensive medical care for government employees and pensioners',
    eligibility: 'Central Government employees, pensioners, and their dependents',
    documents: ['Aadhaar Card', 'Service Certificate', 'Pension Document'],
    applyUrl: 'https://cghs.gov.in/',
    premium: 'Monthly contribution based on pay',
    coverageAmount: 'Full coverage',
    familiesCovered: 'Millions of beneficiaries',
    priority: 'other',
  },
  {
    id: '3',
    name: 'Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Maternal Health',
    coverage: 'Free antenatal care and checkups',
    benefit: 'Free antenatal checkups, supplements, and consultations on 9th of every month',
    eligibility: 'All pregnant women across India',
    documents: ['Aadhaar Card', 'Pregnancy Card'],
    applyUrl: 'https://pmsma.nhp.gov.in/',
    premium: 'Free',
    coverageAmount: 'Free checkups',
    familiesCovered: 'All pregnant women',
    priority: 'state',
  },
  {
    id: '4',
    name: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    ministry: 'Ministry of Finance',
    category: 'Accident Insurance',
    coverage: '₹2,00,000 on accidental death',
    benefit: 'Accident insurance coverage of ₹2 lakh with ₹12 annual premium',
    eligibility: 'All bank account holders aged 18-70 years',
    documents: ['Aadhaar Card', 'Bank Account', 'Mobile Number'],
    applyUrl: 'https://jansuraksha.gov.in/',
    premium: '₹12/year',
    coverageAmount: '₹2,00,000',
    familiesCovered: 'Millions of citizens',
    priority: 'other',
  },
  {
    id: '5',
    name: 'Janani Shishu Suraksha Karyakram (JSSK)',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Maternal & Child Health',
    coverage: 'Free delivery and treatment',
    benefit: 'Free delivery, C-section, medicines, and diet for pregnant women',
    eligibility: 'All pregnant women delivering in government health facilities',
    documents: ['Aadhaar Card', 'Pregnancy Card'],
    applyUrl: 'https://nhm.gov.in/',
    premium: 'Free',
    coverageAmount: 'Fully free',
    familiesCovered: 'All eligible mothers',
    priority: 'state',
  },
  {
    id: '6',
    name: 'Ayushman Bharat Health and Wellness Centers',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Primary Healthcare',
    coverage: 'Free primary healthcare',
    benefit: 'Free primary healthcare services including screening, medicines, and telemedicine',
    eligibility: 'All citizens living near designated centers',
    documents: ['Aadhaar Card'],
    applyUrl: 'https://ab-hwc.nhp.gov.in/',
    premium: 'Free',
    coverageAmount: 'Fully free',
    familiesCovered: '1.5 lakh+ centers',
    priority: 'ayushman',
  },
  {
    id: '7',
    name: 'Pradhan Mantri Garib Kalyan Package',
    ministry: 'Ministry of Health',
    category: 'COVID Relief',
    coverage: 'Free healthcare during emergencies',
    benefit: 'Special package for free healthcare for beneficiaries during COVID-19',
    eligibility: 'PM-JAY beneficiaries',
    documents: ['Aadhaar Card', 'PM-JAY Card'],
    applyUrl: 'https://pmjay.gov.in/',
    premium: 'Free',
    coverageAmount: '₹5,00,000',
    familiesCovered: '100+ million families',
    priority: 'pmjay',
  },
  {
    id: '8',
    name: 'National AMRIT Pharmacies',
    ministry: 'Ministry of Health & Family Welfare',
    category: 'Medicine',
    coverage: 'Discounted medicines for cancer & cardiac',
    benefit: 'Generic medicines at 50-95% discount on cancer and cardiac drugs',
    eligibility: 'All citizens with valid prescription',
    documents: ['Prescription', 'Medical Report'],
    applyUrl: 'https://amritpharmacy.in/',
    premium: 'No premium',
    coverageAmount: 'Up to 95% discount',
    familiesCovered: 'All citizens',
    priority: 'other',
  },
  {
    id: '9',
    name: 'Senior Citizen Health Insurance',
    ministry: 'Various State Health Departments',
    category: 'Senior Citizen',
    coverage: 'Hospitalization for seniors',
    benefit: 'Health insurance coverage for senior citizens aged 60+',
    eligibility: 'Citizens aged 60 years and above',
    documents: ['Aadhaar Card', 'Age Proof'],
    applyUrl: '#',
    premium: 'Low premium',
    coverageAmount: 'Varies by state',
    familiesCovered: 'Senior citizens',
    priority: 'state',
  },
  {
    id: '10',
    name: 'PMJAY - Kedar Grameen Scheme',
    ministry: 'National Health Authority',
    category: 'Health Insurance',
    coverage: 'Expanded PMJAY coverage',
    benefit: 'Extended coverage for more beneficiaries through state-specific PMJAY variants',
    eligibility: 'As per state eligibility criteria',
    documents: ['Aadhaar Card', 'State Documents'],
    applyUrl: 'https://pmjay.gov.in/',
    premium: 'Free',
    coverageAmount: '₹5,00,000',
    familiesCovered: 'Varies by state',
    priority: 'pmjay',
  },
];

export async function GET(request: NextRequest) {
  return NextResponse.json({ schemes });
}
