export const AD_NETWORK = {
  GOOGLE_ADSENSE: process.env.NEXT_PUBLIC_AD_NETWORK !== 'none',
  ADSTERRA: process.env.NEXT_PUBLIC_AD_NETWORK !== 'none',
  NONE: process.env.NEXT_PUBLIC_AD_NETWORK === 'none',
};

export const ADSENSE_CONFIG = {
  publisherId: process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID || 'ca-pub-5241033119281791',
  enabled: process.env.NEXT_PUBLIC_AD_NETWORK !== 'none' && !!process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID,
};

export const ADSTERRA_CONFIG = {
  isProduction: process.env.NODE_ENV === 'production',
  smartlinkUrl: 'https://www.effectivecpmnetwork.com/rp6e107u?key=5a9989d86b9366ebbd414c55ae27f822',
  nativeWidgetInvoke: 'https://pl29830214.effectivecpmnetwork.com/e7992d424fd5f650df4894bde0f81a68/invoke.js',
  nativeWidgetContainer: 'container-e7992d424fd5f650df4894bde0f81a68',
  popunderSrc: 'https://pl29830215.effectivecpmnetwork.com/6b/3c/a8/6b3ca83ac9d45dd570e4569136f825eb.js',
};

export const HACKATHON_MODE = process.env.NEXT_PUBLIC_HACKATHON_MODE === 'true';

export const AD_SIZES = {
  BANNER: { width: 728, height: 90 },
  LEADERBOARD: { width: 728, height: 90 },
  MEDIUM_RECTANGLE: { width: 300, height: 250 },
  LARGE_RECTANGLE: { width: 336, height: 280 },
  SKYSCRAPER: { width: 160, height: 600 },
  WIDE_SKYSCRAPER: { width: 300, height: 600 },
  SMALL_SQUARE: { width: 200, height: 200 },
  SQUARE: { width: 250, height: 250 },
  MOBILE_BANNER: { width: 320, height: 50 },
  MOBILE_LARGE: { width: 320, height: 100 },
  VERTICAL_160_300: { width: 160, height: 300 },
  HALF_BANNER: { width: 468, height: 60 },
} as const;

export const AD_PLACEMENTS = {
  GLOBAL_HEADER: 'global_header',
  GLOBAL_FOOTER: 'global_footer',
  HOME_AFTER_HERO: 'home_after_hero',
  HOME_BEFORE_AI: 'home_before_ai',
  HOME_IN_BLOG: 'home_in_blog',
  HOSPITALS_BEFORE_LIST: 'hospitals_before_list',
  DOCTORS_BEFORE_LIST: 'doctors_before_list',
  SPECIALISTS_BEFORE_LIST: 'specialists_before_list',
  PHARMACIES_BEFORE_LIST: 'pharmacies_before_list',
  DASHBOARD_SIDEBAR: 'dashboard_sidebar',
  DASHBOARD_BETWEEN: 'dashboard_between',
  BOOKING_SIDEBAR: 'booking_sidebar',
  SYMPTOMS_SIDEBAR: 'symptoms_sidebar',
  AI_CHAT_ABOVE_INPUT: 'ai_chat_above_input',
  BLOGS_IN_FEED: 'blogs_in_feed',
  EMERGENCY_AFTER_DIAL: 'emergency_after_dial',
  HEALTH_TRACKER_BETWEEN: 'health_tracker_between',
  PHARMACY_IN_FEED: 'pharmacy_in_feed',
  MAP_OVERLAY: 'map_overlay',
  WELLNESS_BETWEEN: 'wellness_between',
  BEDS_SIDEBAR: 'beds_sidebar',
  FAMILY_CARE_BETWEEN: 'family_care_between',
  COMMUNITIES_BETWEEN: 'communities_between',
  FIRST_AID_SIDEBAR: 'first_aid_sidebar',
  PILL_SCANNER_RESULTS: 'pill_scanner_results',
  BLOOD_DONORS_BETWEEN: 'blood_donors_between',
  HOME_AFTER_FEATURES: 'home_after_features',
} as const;

export type AdPlacement = (typeof AD_PLACEMENTS)[keyof typeof AD_PLACEMENTS];

export type AdSize = keyof typeof AD_SIZES;

export interface AdPlacementConfig {
  id: AdPlacement;
  label: string;
  defaultSize: AdSize;
  adsterraKey?: string;
  googleAdSlot?: string;
  priority: number;
  maxPerPage: number;
  enabled: boolean;
  mobileFriendly: boolean;
}

export const ADSTERRA_SLOTS: Record<AdPlacement, AdPlacementConfig> = {
  [AD_PLACEMENTS.GLOBAL_HEADER]: {
    id: AD_PLACEMENTS.GLOBAL_HEADER,
    label: 'Global Header Banner',
    defaultSize: 'BANNER',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 1,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.GLOBAL_FOOTER]: {
    id: AD_PLACEMENTS.GLOBAL_FOOTER,
    label: 'Global Footer Banner',
    defaultSize: 'BANNER',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 2,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.HOME_AFTER_FEATURES]: {
    id: AD_PLACEMENTS.HOME_AFTER_FEATURES,
    label: 'Homepage After Features',
    defaultSize: 'LEADERBOARD',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 3,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.HOME_AFTER_HERO]: {
    id: AD_PLACEMENTS.HOME_AFTER_HERO,
    label: 'Homepage After Hero',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 4,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.HOME_BEFORE_AI]: {
    id: AD_PLACEMENTS.HOME_BEFORE_AI,
    label: 'Homepage Before AI Section',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 5,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.HOME_IN_BLOG]: {
    id: AD_PLACEMENTS.HOME_IN_BLOG,
    label: 'Homepage In Blog Section',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 6,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.HOSPITALS_BEFORE_LIST]: {
    id: AD_PLACEMENTS.HOSPITALS_BEFORE_LIST,
    label: 'Hospitals Before List',
    defaultSize: 'LEADERBOARD',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 7,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.DOCTORS_BEFORE_LIST]: {
    id: AD_PLACEMENTS.DOCTORS_BEFORE_LIST,
    label: 'Doctors Before List',
    defaultSize: 'LEADERBOARD',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 7,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.SPECIALISTS_BEFORE_LIST]: {
    id: AD_PLACEMENTS.SPECIALISTS_BEFORE_LIST,
    label: 'Specialists Before List',
    defaultSize: 'LEADERBOARD',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 8,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.PHARMACIES_BEFORE_LIST]: {
    id: AD_PLACEMENTS.PHARMACIES_BEFORE_LIST,
    label: 'Pharmacies Before List',
    defaultSize: 'LEADERBOARD',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 9,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.DASHBOARD_SIDEBAR]: {
    id: AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    label: 'Dashboard Sidebar',
    defaultSize: 'SKYSCRAPER',
    adsterraKey: 'f16747272d0330adf3e7bdb1f3307055',
    priority: 10,
    maxPerPage: 2,
    enabled: true,
    mobileFriendly: false,
  },
  [AD_PLACEMENTS.DASHBOARD_BETWEEN]: {
    id: AD_PLACEMENTS.DASHBOARD_BETWEEN,
    label: 'Dashboard Between Sections',
    defaultSize: 'HALF_BANNER',
    adsterraKey: 'fb6de8ddc9af977f8503eb5c4d3e4be8',
    priority: 11,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.BOOKING_SIDEBAR]: {
    id: AD_PLACEMENTS.BOOKING_SIDEBAR,
    label: 'Booking Sidebar',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 12,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: false,
  },
  [AD_PLACEMENTS.SYMPTOMS_SIDEBAR]: {
    id: AD_PLACEMENTS.SYMPTOMS_SIDEBAR,
    label: 'Symptoms Sidebar',
    defaultSize: 'VERTICAL_160_300',
    adsterraKey: '7866ee9b32ed77bd0d7826e490252370',
    priority: 13,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: false,
  },
  [AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT]: {
    id: AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT,
    label: 'AI Chat Above Input',
    defaultSize: 'HALF_BANNER',
    adsterraKey: 'fb6de8ddc9af977f8503eb5c4d3e4be8',
    priority: 14,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.BLOGS_IN_FEED]: {
    id: AD_PLACEMENTS.BLOGS_IN_FEED,
    label: 'Blogs In-Feed',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 15,
    maxPerPage: 2,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.EMERGENCY_AFTER_DIAL]: {
    id: AD_PLACEMENTS.EMERGENCY_AFTER_DIAL,
    label: 'Emergency After Quick Dial',
    defaultSize: 'BANNER',
    adsterraKey: 'a1685be714b0be3828264ce448d114a2',
    priority: 16,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN]: {
    id: AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN,
    label: 'Health Tracker Between',
    defaultSize: 'HALF_BANNER',
    adsterraKey: 'fb6de8ddc9af977f8503eb5c4d3e4be8',
    priority: 17,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.PHARMACY_IN_FEED]: {
    id: AD_PLACEMENTS.PHARMACY_IN_FEED,
    label: 'Pharmacy In-Feed',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 18,
    maxPerPage: 2,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.MAP_OVERLAY]: {
    id: AD_PLACEMENTS.MAP_OVERLAY,
    label: 'Map Overlay',
    defaultSize: 'SMALL_SQUARE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 19,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.WELLNESS_BETWEEN]: {
    id: AD_PLACEMENTS.WELLNESS_BETWEEN,
    label: 'Wellness Between Sections',
    defaultSize: 'HALF_BANNER',
    adsterraKey: 'fb6de8ddc9af977f8503eb5c4d3e4be8',
    priority: 20,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.BEDS_SIDEBAR]: {
    id: AD_PLACEMENTS.BEDS_SIDEBAR,
    label: 'Beds Sidebar',
    defaultSize: 'VERTICAL_160_300',
    adsterraKey: '7866ee9b32ed77bd0d7826e490252370',
    priority: 21,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: false,
  },
  [AD_PLACEMENTS.FAMILY_CARE_BETWEEN]: {
    id: AD_PLACEMENTS.FAMILY_CARE_BETWEEN,
    label: 'Family Care Between',
    defaultSize: 'HALF_BANNER',
    adsterraKey: 'fb6de8ddc9af977f8503eb5c4d3e4be8',
    priority: 22,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.COMMUNITIES_BETWEEN]: {
    id: AD_PLACEMENTS.COMMUNITIES_BETWEEN,
    label: 'Communities Between',
    defaultSize: 'HALF_BANNER',
    adsterraKey: 'fb6de8ddc9af977f8503eb5c4d3e4be8',
    priority: 23,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.FIRST_AID_SIDEBAR]: {
    id: AD_PLACEMENTS.FIRST_AID_SIDEBAR,
    label: 'First Aid Sidebar',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 24,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: false,
  },
  [AD_PLACEMENTS.PILL_SCANNER_RESULTS]: {
    id: AD_PLACEMENTS.PILL_SCANNER_RESULTS,
    label: 'Pill Scanner Results',
    defaultSize: 'MEDIUM_RECTANGLE',
    adsterraKey: 'f433195667474ccbdb91088cdab5ec23',
    priority: 25,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
  [AD_PLACEMENTS.BLOOD_DONORS_BETWEEN]: {
    id: AD_PLACEMENTS.BLOOD_DONORS_BETWEEN,
    label: 'Blood Donors Between',
    defaultSize: 'HALF_BANNER',
    adsterraKey: 'fb6de8ddc9af977f8503eb5c4d3e4be8',
    priority: 26,
    maxPerPage: 1,
    enabled: true,
    mobileFriendly: true,
  },
};

export const PAGE_AD_PLACEMENTS: Record<string, AdPlacement[]> = {
  '/': [
    AD_PLACEMENTS.HOME_AFTER_HERO,
    AD_PLACEMENTS.HOME_BEFORE_AI,
    AD_PLACEMENTS.HOME_IN_BLOG,
    AD_PLACEMENTS.HOME_AFTER_FEATURES,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/hospitals': [
    AD_PLACEMENTS.HOSPITALS_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/doctors': [
    AD_PLACEMENTS.DOCTORS_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/specialists': [
    AD_PLACEMENTS.SPECIALISTS_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/pharmacies': [
    AD_PLACEMENTS.PHARMACIES_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/dashboard': [
    AD_PLACEMENTS.DASHBOARD_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/booking': [
    AD_PLACEMENTS.BOOKING_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/symptoms': [
    AD_PLACEMENTS.SYMPTOMS_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/symptom-checker': [
    AD_PLACEMENTS.SYMPTOMS_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/ai-health-coach': [
    AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/clinical-ai': [
    AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/edge-ai-symptoms': [
    AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/blogs': [
    AD_PLACEMENTS.BLOGS_IN_FEED,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/emergency': [
    AD_PLACEMENTS.EMERGENCY_AFTER_DIAL,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/health-tracker': [
    AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/pharmacy': [
    AD_PLACEMENTS.PHARMACY_IN_FEED,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/map': [
    AD_PLACEMENTS.MAP_OVERLAY,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/wellness': [
    AD_PLACEMENTS.WELLNESS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/beds': [
    AD_PLACEMENTS.BEDS_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/family-care': [
    AD_PLACEMENTS.FAMILY_CARE_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/communities': [
    AD_PLACEMENTS.COMMUNITIES_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/first-aid': [
    AD_PLACEMENTS.FIRST_AID_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/pill-scanner': [
    AD_PLACEMENTS.PILL_SCANNER_RESULTS,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/blood-donors': [
    AD_PLACEMENTS.BLOOD_DONORS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/health-records': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/health-wallet': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/telehealth': [
    AD_PLACEMENTS.HOSPITALS_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/labs': [
    AD_PLACEMENTS.PHARMACIES_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/ambulance': [
    AD_PLACEMENTS.EMERGENCY_AFTER_DIAL,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/analytics': [
    AD_PLACEMENTS.DASHBOARD_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/chat': [
    AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/vane-chat': [
    AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/camps': [
    AD_PLACEMENTS.WELLNESS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/subscription': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/video-consult': [
    AD_PLACEMENTS.HOSPITALS_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/voice-emergency': [
    AD_PLACEMENTS.EMERGENCY_AFTER_DIAL,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/sms-emergency': [
    AD_PLACEMENTS.EMERGENCY_AFTER_DIAL,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/medicine-reminder': [
    AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/medications': [
    AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/health-risk': [
    AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/wearables': [
    AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/womens-health': [
    AD_PLACEMENTS.FAMILY_CARE_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/pets': [
    AD_PLACEMENTS.FAMILY_CARE_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/blockchain-records': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/digital-twin': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/data-marketplace': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/micro-insurance': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/health-id': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/organ-matching': [
    AD_PLACEMENTS.BLOOD_DONORS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/drone-network': [
    AD_PLACEMENTS.EMERGENCY_AFTER_DIAL,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/offline-mesh': [
    AD_PLACEMENTS.EMERGENCY_AFTER_DIAL,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/rewards': [
    AD_PLACEMENTS.DASHBOARD_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/predictive-analytics': [
    AD_PLACEMENTS.DASHBOARD_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/hospital-dashboard': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/hospital-partner': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/pharmacy-partner': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/hospital-inventory': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/lab-booking': [
    AD_PLACEMENTS.BOOKING_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/medicine-verify': [
    AD_PLACEMENTS.PILL_SCANNER_RESULTS,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/schemes': [
    AD_PLACEMENTS.WELLNESS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/corporate-wellness': [
    AD_PLACEMENTS.WELLNESS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/contact': [
    AD_PLACEMENTS.WELLNESS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/feedback': [
    AD_PLACEMENTS.WELLNESS_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/install': [
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/auth/*': [
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/hospitals/*': [
    AD_PLACEMENTS.HOSPITALS_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/doctors/*': [
    AD_PLACEMENTS.DOCTORS_BEFORE_LIST,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/blogs/*': [
    AD_PLACEMENTS.BLOGS_IN_FEED,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/health/*': [
    AD_PLACEMENTS.HEALTH_TRACKER_BETWEEN,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
  '/admin/*': [
    AD_PLACEMENTS.DASHBOARD_SIDEBAR,
    AD_PLACEMENTS.GLOBAL_HEADER,
    AD_PLACEMENTS.GLOBAL_FOOTER,
  ],
};

export const ADSTERRA_TOP_10_SLOTS: AdPlacement[] = [
  AD_PLACEMENTS.GLOBAL_HEADER,
  AD_PLACEMENTS.GLOBAL_FOOTER,
  AD_PLACEMENTS.HOME_AFTER_HERO,
  AD_PLACEMENTS.HOME_BEFORE_AI,
  AD_PLACEMENTS.HOME_IN_BLOG,
  AD_PLACEMENTS.HOSPITALS_BEFORE_LIST,
  AD_PLACEMENTS.DOCTORS_BEFORE_LIST,
  AD_PLACEMENTS.DASHBOARD_SIDEBAR,
  AD_PLACEMENTS.BOOKING_SIDEBAR,
  AD_PLACEMENTS.AI_CHAT_ABOVE_INPUT,
];
