import type { MetadataRoute } from 'next';

const BASE = process.env.NEXT_PUBLIC_APP_URL || 'https://zyntracare.com';

const BLOG_SLUGS = [
  'managing-high-blood-pressure-naturally', 'plant-based-nutrition-guide-india',
  'mental-health-digital-age-balance', 'yoga-beginners-5-poses-morning',
  'understanding-diabetes-prevention-early-warning', 'eye-care-tips-screen-generation',
  'science-of-sleep-fix-schedule', 'immunity-boosters-ayurvedic-secrets',
  'daily-water-intake-guide', 'signs-of-dehydration-warning',
  'viral-fever-symptoms-treatment', 'dengue-fever-prevention-guide',
  'typhoid-fever-recovery-diet', 'home-remedies-cough-cold',
  'dry-cough-vs-wet-cough-treatment', 'tension-headache-vs-migraine',
  'natural-headache-relief-remedies', 'heart-attack-symptoms-women-men',
  'cholesterol-levels-diet-indians', 'blood-sugar-levels-normal-range',
  'diabetes-diet-indian-food', 'acidity-heartburn-relief-remedies',
  'constipation-relief-natural-remedies', 'food-poisoning-treatment-recovery',
  'pcos-symptoms-diet-treatment', 'iron-deficiency-anemia-diet',
  'pregnancy-diet-trimester-guide', 'vitamin-d-deficiency-india',
  'vitamin-b12-deficiency-vegetarians', 'cpr-steps-emergency-guide',
  'snake-bite-first-aid-guide', 'monsoon-health-tips-seasonal-diseases',
  'summer-health-tips-heat-hydration', 'acne-treatment-indian-skin',
  'hair-fall-causes-treatments', 'protein-requirements-indian-diet',
  'weight-loss-diet-plan-indians', 'long-covid-symptoms-recovery',
];

const ROUTES: { path: string; priority: number; changeFreq: 'daily' | 'weekly' | 'monthly' }[] = [
  { path: '/', priority: 1.0, changeFreq: 'daily' },
  { path: '/emergency', priority: 0.9, changeFreq: 'daily' },
  { path: '/hospitals', priority: 0.9, changeFreq: 'daily' },
  { path: '/doctors', priority: 0.9, changeFreq: 'daily' },
  { path: '/specialists', priority: 0.9, changeFreq: 'daily' },
  { path: '/labs', priority: 0.8, changeFreq: 'daily' },
  { path: '/pharmacies', priority: 0.8, changeFreq: 'daily' },
  { path: '/booking', priority: 0.8, changeFreq: 'daily' },
  { path: '/ambulance', priority: 0.8, changeFreq: 'daily' },
  { path: '/blood-donors', priority: 0.8, changeFreq: 'daily' },
  { path: '/pets', priority: 0.8, changeFreq: 'daily' },
  { path: '/blogs', priority: 0.8, changeFreq: 'daily' },
  { path: '/health', priority: 0.8, changeFreq: 'weekly' },
  { path: '/symptoms', priority: 0.7, changeFreq: 'weekly' },
  { path: '/beds', priority: 0.7, changeFreq: 'daily' },
  { path: '/telehealth', priority: 0.7, changeFreq: 'weekly' },
  { path: '/video-consult', priority: 0.7, changeFreq: 'weekly' },
  { path: '/medicine-reminder', priority: 0.6, changeFreq: 'weekly' },
  { path: '/medicine-verify', priority: 0.6, changeFreq: 'weekly' },
  { path: '/camps', priority: 0.6, changeFreq: 'weekly' },
  { path: '/chat', priority: 0.5, changeFreq: 'weekly' },
  { path: '/contact', priority: 0.5, changeFreq: 'monthly' },
  { path: '/first-aid', priority: 0.6, changeFreq: 'weekly' },

  // Health topics (high SEO value)
  { path: '/health/water-intake', priority: 0.8, changeFreq: 'weekly' },
  { path: '/health/fever', priority: 0.8, changeFreq: 'weekly' },
  { path: '/health/headache', priority: 0.8, changeFreq: 'weekly' },
  { path: '/health/cold-and-flu', priority: 0.8, changeFreq: 'weekly' },
  { path: '/health/blood-pressure', priority: 0.8, changeFreq: 'weekly' },
  { path: '/health/diabetes', priority: 0.8, changeFreq: 'weekly' },
  { path: '/health/heart-health', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/nutrition', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/mental-health', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/vaccination', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/stress-management', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/sleep', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/exercise', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/covid-19', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/allergies', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/vitamins', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/yoga', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/dental-care', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/skin-care', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/immunity', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/digestion', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/weight-loss', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/pregnancy', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/child-health', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/senior-care', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/ayurveda', priority: 0.6, changeFreq: 'weekly' },
  { path: '/health/home-remedies', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/first-aid-guide', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/dehydration', priority: 0.7, changeFreq: 'weekly' },
  { path: '/health/eye-care', priority: 0.6, changeFreq: 'weekly' },

  // Support pages
  { path: '/subscription', priority: 0.4, changeFreq: 'monthly' },
  { path: '/rewards', priority: 0.4, changeFreq: 'monthly' },
  { path: '/faq', priority: 0.5, changeFreq: 'monthly' },
  { path: '/legal/privacy', priority: 0.3, changeFreq: 'monthly' },
  { path: '/legal/terms', priority: 0.3, changeFreq: 'monthly' },
  { path: '/accessibility-mode', priority: 0.3, changeFreq: 'monthly' },
  { path: '/feedback', priority: 0.3, changeFreq: 'monthly' },
  { path: '/sponsor', priority: 0.3, changeFreq: 'monthly' },
  { path: '/install', priority: 0.2, changeFreq: 'monthly' },
  { path: '/doctor/register', priority: 0.4, changeFreq: 'weekly' },

  // Feature pages
  { path: '/ai-health-coach', priority: 0.6, changeFreq: 'weekly' },
  { path: '/ai-vision', priority: 0.5, changeFreq: 'weekly' },
  { path: '/clinical-ai', priority: 0.5, changeFreq: 'weekly' },
  { path: '/clinical-scribe', priority: 0.5, changeFreq: 'weekly' },
  { path: '/digital-twin', priority: 0.5, changeFreq: 'weekly' },
  { path: '/edge-ai-symptoms', priority: 0.5, changeFreq: 'weekly' },
  { path: '/edge-ai-vision', priority: 0.5, changeFreq: 'weekly' },
  { path: '/vane-chat', priority: 0.5, changeFreq: 'weekly' },
  { path: '/pill-scanner', priority: 0.5, changeFreq: 'weekly' },
  { path: '/predictive-analytics', priority: 0.5, changeFreq: 'weekly' },
  { path: '/health-risk', priority: 0.5, changeFreq: 'weekly' },
  { path: '/health-tracker', priority: 0.5, changeFreq: 'weekly' },
  { path: '/health-wallet', priority: 0.5, changeFreq: 'weekly' },
  { path: '/health-id', priority: 0.5, changeFreq: 'weekly' },
  { path: '/organ-matching', priority: 0.5, changeFreq: 'weekly' },
  { path: '/micro-insurance', priority: 0.5, changeFreq: 'weekly' },
  { path: '/corporate-wellness', priority: 0.5, changeFreq: 'weekly' },
  { path: '/wellness', priority: 0.5, changeFreq: 'weekly' },
  { path: '/data-marketplace', priority: 0.4, changeFreq: 'weekly' },
  { path: '/drone-network', priority: 0.4, changeFreq: 'weekly' },
  { path: '/mesh-network', priority: 0.4, changeFreq: 'weekly' },
  { path: '/supply-chain', priority: 0.4, changeFreq: 'weekly' },
  { path: '/offline', priority: 0.4, changeFreq: 'weekly' },
  { path: '/offline-mesh', priority: 0.4, changeFreq: 'weekly' },
  { path: '/outbreak-radar', priority: 0.5, changeFreq: 'weekly' },
  { path: '/epidemic-radar', priority: 0.5, changeFreq: 'weekly' },
  { path: '/womens-health', priority: 0.6, changeFreq: 'weekly' },
  { path: '/genomic-dashboard', priority: 0.4, changeFreq: 'weekly' },
  { path: '/multilingual', priority: 0.4, changeFreq: 'weekly' },
  { path: '/chain-reaction', priority: 0.3, changeFreq: 'monthly' },
  { path: '/eye-control', priority: 0.4, changeFreq: 'weekly' },
  { path: '/dementia-voice', priority: 0.4, changeFreq: 'weekly' },
  { path: '/bluetooth-hrm', priority: 0.4, changeFreq: 'weekly' },
  { path: '/voice-emergency', priority: 0.5, changeFreq: 'weekly' },
  { path: '/sms-emergency', priority: 0.5, changeFreq: 'weekly' },
  { path: '/family-care', priority: 0.5, changeFreq: 'weekly' },
  { path: '/medications', priority: 0.5, changeFreq: 'weekly' },
  { path: '/pdf-prescription', priority: 0.4, changeFreq: 'weekly' },
  { path: '/medical-id', priority: 0.4, changeFreq: 'weekly' },
  { path: '/health-records', priority: 0.5, changeFreq: 'weekly' },
  { path: '/schemes', priority: 0.5, changeFreq: 'weekly' },
  { path: '/blockchain-records', priority: 0.4, changeFreq: 'weekly' },
  { path: '/hospital-partner', priority: 0.4, changeFreq: 'weekly' },
  { path: '/pharmacy-partner', priority: 0.4, changeFreq: 'weekly' },
  { path: '/hospital-dashboard', priority: 0.3, changeFreq: 'monthly' },
  { path: '/hospital-inventory', priority: 0.3, changeFreq: 'monthly' },
  { path: '/pharmacy', priority: 0.4, changeFreq: 'weekly' },
  { path: '/lab-booking', priority: 0.4, changeFreq: 'weekly' },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes = ROUTES.map((r) => ({
    url: `${BASE}${r.path}`,
    lastModified: new Date(),
    changeFrequency: r.changeFreq,
    priority: r.priority,
  }));

  const blogRoutes: MetadataRoute.Sitemap = BLOG_SLUGS.map((slug) => ({
    url: `${BASE}/blogs/${slug}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  return [...staticRoutes, ...blogRoutes];
}
