import { NextRequest, NextResponse } from 'next/server';
import { getToken } from 'next-auth/jwt';
import { prisma } from '@/lib/prisma';

const MEDICINE_DATABASE = [
  { name: 'Paracetamol 500mg', composition: 'Paracetamol 500mg', category: 'Pain Relief', manufacturer: 'Cipla', dosage: '1-2 tablets every 4-6 hours', maxDaily: '8 tablets', sideEffects: 'Nausea, rash', schedule: 'As needed', color: 'White', shape: 'Round' },
  { name: 'Paracetamol 650mg', composition: 'Paracetamol 650mg', category: 'Pain Relief', manufacturer: 'Abbott', dosage: '1 tablet every 6 hours', maxDaily: '4 tablets', sideEffects: 'Nausea, rash', schedule: 'As needed', color: 'White', shape: 'Oval' },
  { name: 'Dolo 650', composition: 'Paracetamol 650mg', category: 'Pain Relief', manufacturer: 'Micro Labs', dosage: '1 tablet every 6 hours', maxDaily: '4 tablets', sideEffects: 'Nausea', schedule: 'After food', color: 'White', shape: 'Tablet' },
  { name: 'Amoxicillin 250mg', composition: 'Amoxicillin 250mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 capsule 3 times daily', maxDaily: '3 capsules', sideEffects: 'Diarrhea, rash', schedule: 'After food', color: 'Yellow/Green', shape: 'Capsule' },
  { name: 'Amoxicillin 500mg', composition: 'Amoxicillin 500mg', category: 'Antibiotic', manufacturer: 'Sun Pharma', dosage: '1 capsule 3 times daily', maxDaily: '3 capsules', sideEffects: 'Diarrhea', schedule: 'After food', color: 'Red/Yellow', shape: 'Capsule' },
  { name: 'Augmentin 625 Duo', composition: 'Amoxicillin 500mg + Clavulanic Acid 125mg', category: 'Antibiotic', manufacturer: 'GSK', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Diarrhea, nausea', schedule: 'With food', color: 'White', shape: 'Oval' },
  { name: 'Azithromycin 250mg', composition: 'Azithromycin 250mg', category: 'Antibiotic', manufacturer: 'Alkem', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Nausea, abdominal pain', schedule: 'Empty stomach', color: 'White', shape: 'Tablet' },
  { name: 'Azithromycin 500mg', composition: 'Azithromycin 500mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet daily for 3 days', maxDaily: '1 tablet', sideEffects: 'Nausea', schedule: 'Empty stomach', color: 'White', shape: 'Tablet' },
  { name: 'Cefixime 200mg', composition: 'Cefixime 200mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Diarrhea, indigestion', schedule: 'After food', color: 'White', shape: 'Tablet' },
  { name: 'Norfloxacin 400mg', composition: 'Norfloxacin 400mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Nausea, dizziness', schedule: 'Empty stomach', color: 'White', shape: 'Tablet' },
  { name: 'Metformin 500mg', composition: 'Metformin 500mg', category: 'Anti-Diabetic', manufacturer: 'USV', dosage: '1 tablet twice daily with meals', maxDaily: '3 tablets', sideEffects: 'Nausea, metallic taste', schedule: 'With meals', color: 'White', shape: 'Round' },
  { name: 'Metformin 1000mg', composition: 'Metformin 1000mg', category: 'Anti-Diabetic', manufacturer: 'USV', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'GI upset', schedule: 'With meals', color: 'White', shape: 'Oval' },
  { name: 'Glycomet 500', composition: 'Metformin 500mg', category: 'Anti-Diabetic', manufacturer: 'USV', dosage: '1 tablet twice daily', maxDaily: '3 tablets', sideEffects: 'Nausea', schedule: 'With food', color: 'White', shape: 'Round' },
  { name: 'Glimepiride 1mg', composition: 'Glimepiride 1mg', category: 'Anti-Diabetic', manufacturer: 'Sanofi', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Hypoglycemia, dizziness', schedule: 'With breakfast', color: 'Pink', shape: 'Round' },
  { name: 'Glimepiride 2mg', composition: 'Glimepiride 2mg', category: 'Anti-Diabetic', manufacturer: 'Sanofi', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Hypoglycemia', schedule: 'With breakfast', color: 'Green', shape: 'Round' },
  { name: 'Teneligliptin 20mg', composition: 'Teneligliptin 20mg', category: 'Anti-Diabetic', manufacturer: 'Zydus', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Hypoglycemia', schedule: 'After breakfast', color: 'White', shape: 'Round' },
  { name: 'Amlodipine 5mg', composition: 'Amlodipine 5mg', category: 'Cardiovascular', manufacturer: 'Pfizer', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Ankle swelling, headache', schedule: 'Morning', color: 'White', shape: 'Tablet' },
  { name: 'Amlodipine 10mg', composition: 'Amlodipine 10mg', category: 'Cardiovascular', manufacturer: 'Sun Pharma', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Ankle swelling', schedule: 'Morning', color: 'White', shape: 'Tablet' },
  { name: 'Telmisartan 40mg', composition: 'Telmisartan 40mg', category: 'Cardiovascular', manufacturer: 'Boehringer', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Dizziness', schedule: 'Morning', color: 'White', shape: 'Tablet' },
  { name: 'Telmisartan 80mg', composition: 'Telmisartan 80mg', category: 'Cardiovascular', manufacturer: 'Boehringer', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Dizziness, fatigue', schedule: 'Morning', color: 'Blue', shape: 'Tablet' },
  { name: 'Losartan 25mg', composition: 'Losartan 25mg', category: 'Cardiovascular', manufacturer: 'Merck', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Dizziness', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Losartan 50mg', composition: 'Losartan 50mg', category: 'Cardiovascular', manufacturer: 'Merck', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Dizziness, cough', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Atorvastatin 10mg', composition: 'Atorvastatin 10mg', category: 'Cardiovascular', manufacturer: 'Pfizer', dosage: '1 tablet at night', maxDaily: '1 tablet', sideEffects: 'Muscle pain', schedule: 'Night', color: 'White', shape: 'Oval' },
  { name: 'Atorvastatin 20mg', composition: 'Atorvastatin 20mg', category: 'Cholesterol', manufacturer: 'Pfizer', dosage: '1 tablet at night', maxDaily: '1 tablet', sideEffects: 'Muscle pain', schedule: 'Night', color: 'White', shape: 'Oval' },
  { name: 'Rosuvastatin 10mg', composition: 'Rosuvastatin 10mg', category: 'Cholesterol', manufacturer: 'Crestor', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Muscle aches', schedule: 'Any time', color: 'White', shape: 'Round' },
  { name: 'Aspirin 75mg', composition: 'Aspirin 75mg', category: 'Cardiovascular', manufacturer: 'Bayer', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'GI bleeding', schedule: 'After food', color: 'White', shape: 'Round' },
  { name: 'Aspirin 150mg', composition: 'Aspirin 150mg', category: 'Cardiovascular', manufacturer: 'Bayer', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Heartburn', schedule: 'After food', color: 'White', shape: 'Round' },
  { name: 'Clopidogrel 75mg', composition: 'Clopidogrel 75mg', category: 'Cardiovascular', manufacturer: 'Sanofi', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Bruising', schedule: 'Any time', color: 'Pink', shape: 'Round' },
  { name: 'Metoprolol 25mg', composition: 'Metoprolol 25mg', category: 'Cardiovascular', manufacturer: 'AstraZeneca', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Fatigue, slow heart rate', schedule: 'With meals', color: 'White', shape: 'Round' },
  { name: 'Omeprazole 20mg', composition: 'Omeprazole 20mg', category: 'Gastrointestinal', manufacturer: 'AstraZeneca', dosage: '1 capsule daily before breakfast', maxDaily: '1 capsule', sideEffects: 'Headache, gas', schedule: 'Empty stomach', color: 'Pink', shape: 'Capsule' },
  { name: 'Omeprazole 40mg', composition: 'Omeprazole 40mg', category: 'Gastrointestinal', manufacturer: 'Dr Reddy', dosage: '1 capsule daily before breakfast', maxDaily: '1 capsule', sideEffects: 'Headache', schedule: 'Empty stomach', color: 'Pink/Brown', shape: 'Capsule' },
  { name: 'Pantoprazole 40mg', composition: 'Pantoprazole 40mg', category: 'Gastrointestinal', manufacturer: 'Pfizer', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Nausea, flatulence', schedule: 'Empty stomach', color: 'Yellow', shape: 'Tablet' },
  { name: 'Ranitidine 150mg', composition: 'Ranitidine 150mg', category: 'Gastrointestinal', manufacturer: 'GSK', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Headache, constipation', schedule: 'After meals', color: 'White', shape: 'Round' },
  { name: 'Domperidone 10mg', composition: 'Domperidone 10mg', category: 'Gastrointestinal', manufacturer: 'Janssen', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Dry mouth', schedule: 'Before meals', color: 'White', shape: 'Round' },
  { name: 'Ondansetron 4mg', composition: 'Ondansetron 4mg', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 tablet as needed', maxDaily: '3 tablets', sideEffects: 'Headache, fatigue', schedule: 'As needed', color: 'White', shape: 'Tablet' },
  { name: 'Ibuprofen 200mg', composition: 'Ibuprofen 200mg', category: 'Pain Relief', manufacturer: 'Abbott', dosage: '1-2 tablets every 6-8 hours', maxDaily: '6 tablets', sideEffects: 'Stomach pain, heartburn', schedule: 'After food', color: 'Orange', shape: 'Round' },
  { name: 'Ibuprofen 400mg', composition: 'Ibuprofen 400mg', category: 'Pain Relief', manufacturer: 'Cipla', dosage: '1 tablet every 6-8 hours', maxDaily: '3 tablets', sideEffects: 'GI upset', schedule: 'After food', color: 'Orange', shape: 'Round' },
  { name: 'Diclofenac 50mg', composition: 'Diclofenac 50mg', category: 'Pain Relief', manufacturer: 'Novartis', dosage: '1 tablet 2-3 times daily', maxDaily: '3 tablets', sideEffects: 'Stomach pain', schedule: 'After food', color: 'Yellow', shape: 'Tablet' },
  { name: 'Mefenamic Acid 250mg', composition: 'Mefenamic Acid 250mg', category: 'Pain Relief', manufacturer: 'Parke Davis', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Diarrhea, nausea', schedule: 'After food', color: 'Blue', shape: 'Capsule' },
  { name: 'Naproxen 250mg', composition: 'Naproxen 250mg', category: 'Pain Relief', manufacturer: 'RPG Life', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Heartburn', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'Cetirizine 10mg', composition: 'Cetirizine 10mg', category: 'Allergy', manufacturer: 'UCB', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Drowsiness', schedule: 'Night', color: 'White', shape: 'Round' },
  { name: 'Levocetirizine 5mg', composition: 'Levocetirizine 5mg', category: 'Allergy', manufacturer: 'Dr Reddy', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Drowsiness', schedule: 'Night', color: 'White', shape: 'Round' },
  { name: 'Fexofenadine 120mg', composition: 'Fexofenadine 120mg', category: 'Allergy', manufacturer: 'Sanofi', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Headache', schedule: 'Morning', color: 'White', shape: 'Oval' },
  { name: 'Montelukast 10mg', composition: 'Montelukast 10mg', category: 'Respiratory', manufacturer: 'MSD', dosage: '1 tablet at night', maxDaily: '1 tablet', sideEffects: 'Headache, thirst', schedule: 'Night', color: 'White', shape: 'Round' },
  { name: 'Montelukast 5mg (Chewable)', composition: 'Montelukast 5mg', category: 'Respiratory', manufacturer: 'MSD', dosage: '1 tablet at night', maxDaily: '1 tablet', sideEffects: 'Headache', schedule: 'Night', color: 'Pink', shape: 'Round' },
  { name: 'Salbutamol Inhaler', composition: 'Salbutamol 100mcg', category: 'Respiratory', manufacturer: 'Cipla', dosage: '1-2 puffs as needed', maxDaily: '8 puffs', sideEffects: 'Tremor, increased heart rate', schedule: 'As needed', color: 'Blue', shape: 'Inhaler' },
  { name: 'Formoterol + Budesonide Inhaler', composition: 'Formoterol 6mcg + Budesonide 200mcg', category: 'Respiratory', manufacturer: 'AstraZeneca', dosage: '1 puff twice daily', maxDaily: '2 puffs', sideEffects: 'Throat irritation', schedule: '12 hourly', color: 'White', shape: 'Inhaler' },
  { name: 'Vitamin D3 60K', composition: 'Cholecalciferol 60000IU', category: 'Supplement', manufacturer: 'Abbott', dosage: '1 capsule weekly', maxDaily: '1 capsule', sideEffects: 'None typically', schedule: 'After breakfast', color: 'White', shape: 'Capsule' },
  { name: 'Vitamin B Complex', composition: 'B1 10mg + B6 3mg + B12 15mcg', category: 'Supplement', manufacturer: 'Merck', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'None', schedule: 'After breakfast', color: 'Yellow', shape: 'Round' },
  { name: 'Vitamin C 500mg', composition: 'Ascorbic Acid 500mg', category: 'Supplement', manufacturer: 'Cipla', dosage: '1 tablet daily', maxDaily: '2 tablets', sideEffects: 'None', schedule: 'Any time', color: 'Orange', shape: 'Round' },
  { name: 'Calcium + Vitamin D3', composition: 'Calcium 500mg + Vit D3 400IU', category: 'Supplement', manufacturer: 'GSK', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Constipation', schedule: 'With meals', color: 'White', shape: 'Oval' },
  { name: 'Iron + Folic Acid', composition: 'Ferrous Sulfate 100mg + Folic Acid 5mg', category: 'Supplement', manufacturer: 'Cipla', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Constipation, dark stools', schedule: 'Empty stomach', color: 'Red', shape: 'Tablet' },
  { name: 'Zinc 20mg', composition: 'Zinc Sulfate 20mg', category: 'Supplement', manufacturer: 'Dr Reddy', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Metallic taste', schedule: 'After food', color: 'White', shape: 'Round' },
  { name: 'Fluconazole 150mg', composition: 'Fluconazole 150mg', category: 'Antifungal', manufacturer: 'Cipla', dosage: '1 capsule single dose', maxDaily: '1 capsule', sideEffects: 'Nausea, headache', schedule: 'Single dose', color: 'White', shape: 'Capsule' },
  { name: 'Terbinafine 250mg', composition: 'Terbinafine 250mg', category: 'Antifungal', manufacturer: 'Novartis', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Headache, GI upset', schedule: 'After food', color: 'White', shape: 'Tablet' },
  { name: 'Clotrimazole Cream', composition: 'Clotrimazole 1%', category: 'Antifungal', manufacturer: 'GSK', dosage: 'Apply twice daily', maxDaily: 'Topical', sideEffects: 'Local irritation', schedule: '12 hourly', color: 'White', shape: 'Cream' },
  { name: 'Acyclovir 400mg', composition: 'Acyclovir 400mg', category: 'Antiviral', manufacturer: 'Cipla', dosage: '1 tablet 5 times daily', maxDaily: '5 tablets', sideEffects: 'Nausea, headache', schedule: 'Every 4 hours', color: 'White', shape: 'Tablet' },
  { name: 'Oseltamivir 75mg', composition: 'Oseltamivir 75mg', category: 'Antiviral', manufacturer: 'Roche', dosage: '1 capsule twice daily for 5 days', maxDaily: '2 capsules', sideEffects: 'Nausea, vomiting', schedule: 'With food', color: 'White', shape: 'Capsule' },
  { name: 'Prednisolone 10mg', composition: 'Prednisolone 10mg', category: 'Steroid', manufacturer: 'Abbott', dosage: 'As directed by physician', maxDaily: 'As directed', sideEffects: 'Weight gain, diabetes', schedule: 'After breakfast', color: 'White', shape: 'Tablet' },
  { name: 'Prednisolone 20mg', composition: 'Prednisolone 20mg', category: 'Steroid', manufacturer: 'Abbott', dosage: 'As directed by physician', maxDaily: 'As directed', sideEffects: 'Insomnia, increased appetite', schedule: 'After breakfast', color: 'Yellow', shape: 'Tablet' },
  { name: 'Dexamethasone 4mg', composition: 'Dexamethasone 4mg', category: 'Steroid', manufacturer: 'Cipla', dosage: 'As directed', maxDaily: 'As directed', sideEffects: 'Mood changes', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'Levothyroxine 25mcg', composition: 'Levothyroxine 25mcg', category: 'Thyroid', manufacturer: 'Abbott', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Palpitations, anxiety', schedule: 'Empty stomach 30min before breakfast', color: 'Orange', shape: 'Round' },
  { name: 'Levothyroxine 50mcg', composition: 'Levothyroxine 50mcg', category: 'Thyroid', manufacturer: 'Abbott', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Palpitations', schedule: 'Empty stomach', color: 'White', shape: 'Round' },
  { name: 'Levothyroxine 100mcg', composition: 'Levothyroxine 100mcg', category: 'Thyroid', manufacturer: 'Abbott', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Tremors, sweating', schedule: 'Empty stomach', color: 'Yellow', shape: 'Round' },
  { name: 'Alprazolam 0.25mg', composition: 'Alprazolam 0.25mg', category: 'Neurology', manufacturer: 'Pfizer', dosage: '1 tablet as needed', maxDaily: '3 tablets', sideEffects: 'Drowsiness, dependence', schedule: 'As needed', color: 'White', shape: 'Round' },
  { name: 'Alprazolam 0.5mg', composition: 'Alprazolam 0.5mg', category: 'Neurology', manufacturer: 'Pfizer', dosage: '1 tablet as needed', maxDaily: '3 tablets', sideEffects: 'Drowsiness', schedule: 'As needed', color: 'Yellow', shape: 'Oval' },
  { name: 'Clonazepam 0.5mg', composition: 'Clonazepam 0.5mg', category: 'Neurology', manufacturer: 'RPG Life', dosage: '1 tablet at night', maxDaily: '1 tablet', sideEffects: 'Drowsiness, fatigue', schedule: 'Night', color: 'White', shape: 'Round' },
  { name: 'Escitalopram 10mg', composition: 'Escitalopram 10mg', category: 'Neurology', manufacturer: 'Lundbeck', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Nausea, insomnia', schedule: 'Morning', color: 'White', shape: 'Oval' },
  { name: 'Fluoxetine 20mg', composition: 'Fluoxetine 20mg', category: 'Neurology', manufacturer: 'Eli Lilly', dosage: '1 capsule daily', maxDaily: '1 capsule', sideEffects: 'Nausea, anxiety', schedule: 'Morning', color: 'Green/White', shape: 'Capsule' },
  { name: 'Sertraline 50mg', composition: 'Sertraline 50mg', category: 'Neurology', manufacturer: 'Pfizer', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Diarrhea, insomnia', schedule: 'Morning', color: 'White', shape: 'Tablet' },
  { name: 'Gabapentin 100mg', composition: 'Gabapentin 100mg', category: 'Neurology', manufacturer: 'Pfizer', dosage: '1 capsule 3 times daily', maxDaily: '3 capsules', sideEffects: 'Dizziness, drowsiness', schedule: 'With food', color: 'White', shape: 'Capsule' },
  { name: 'Gabapentin 300mg', composition: 'Gabapentin 300mg', category: 'Neurology', manufacturer: 'Sun Pharma', dosage: '1 capsule 3 times daily', maxDaily: '3 capsules', sideEffects: 'Dizziness', schedule: 'With food', color: 'Yellow', shape: 'Capsule' },
  { name: 'Furosemide 40mg', composition: 'Furosemide 40mg', category: 'Cardiovascular', manufacturer: 'Sanofi', dosage: '1 tablet daily', maxDaily: '2 tablets', sideEffects: 'Frequent urination, dehydration', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Spironolactone 25mg', composition: 'Spironolactone 25mg', category: 'Cardiovascular', manufacturer: 'Pfizer', dosage: '1 tablet daily', maxDaily: '2 tablets', sideEffects: 'Hyperkalemia', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Hydrochlorothiazide 12.5mg', composition: 'Hydrochlorothiazide 12.5mg', category: 'Cardiovascular', manufacturer: 'Cipla', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Frequent urination', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Bisoprolol 2.5mg', composition: 'Bisoprolol 2.5mg', category: 'Cardiovascular', manufacturer: 'Merck', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Fatigue, slow pulse', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Bisoprolol 5mg', composition: 'Bisoprolol 5mg', category: 'Cardiovascular', manufacturer: 'Merck', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Fatigue, cold hands', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Carvedilol 3.125mg', composition: 'Carvedilol 3.125mg', category: 'Cardiovascular', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Dizziness, fatigue', schedule: 'With meals', color: 'White', shape: 'Round' },
  { name: 'Digoxin 0.25mg', composition: 'Digoxin 0.25mg', category: 'Cardiovascular', manufacturer: 'GSK', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Nausea, vision changes', schedule: 'Morning', color: 'White', shape: 'Round' },
  { name: 'Warfarin 2mg', composition: 'Warfarin 2mg', category: 'Cardiovascular', manufacturer: 'Bristol Myers', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Bleeding, bruising', schedule: 'Evening', color: 'Lavender', shape: 'Round' },
  { name: 'Warfarin 5mg', composition: 'Warfarin 5mg', category: 'Cardiovascular', manufacturer: 'Bristol Myers', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Bleeding risk', schedule: 'Evening', color: 'Peach', shape: 'Round' },
  { name: 'Cough Syrup (Expectorant)', composition: 'Ambroxol 30mg + Guaiphenesin 50mg', category: 'Respiratory', manufacturer: 'Abbott', dosage: '10ml 3 times daily', maxDaily: '30ml', sideEffects: 'Nausea, drowsiness', schedule: 'After meals', color: 'White', shape: 'Syrup' },
  { name: 'Cough Syrup (Antitussive)', composition: 'Dextromethorphan 10mg', category: 'Respiratory', manufacturer: 'Cipla', dosage: '10ml 3 times daily', maxDaily: '30ml', sideEffects: 'Drowsiness', schedule: 'As needed', color: 'Red', shape: 'Syrup' },
  { name: 'Benzonatate 100mg', composition: 'Benzonatate 100mg', category: 'Respiratory', manufacturer: 'Cipla', dosage: '1 capsule 3 times daily', maxDaily: '3 capsules', sideEffects: 'Dizziness, headache', schedule: 'As needed', color: 'Yellow', shape: 'Capsule' },
  { name: 'Antacid Liquid', composition: 'Aluminum 250mg + Magnesium 250mg', category: 'Gastrointestinal', manufacturer: 'GSK', dosage: '10-20ml as needed', maxDaily: '80ml', sideEffects: 'None', schedule: 'After meals', color: 'White', shape: 'Liquid' },
  { name: 'Loperamide 2mg', composition: 'Loperamide 2mg', category: 'Gastrointestinal', manufacturer: 'Janssen', dosage: '2 tablets initially, then 1 after each loose stool', maxDaily: '8 tablets', sideEffects: 'Constipation', schedule: 'As needed', color: 'White', shape: 'Capsule' },
  { name: 'Metoclopramide 10mg', composition: 'Metoclopramide 10mg', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Drowsiness, restlessness', schedule: '30 min before meals', color: 'White', shape: 'Tablet' },
  { name: 'Ursodeoxycholic Acid 300mg', composition: 'Ursodeoxycholic Acid 300mg', category: 'Gastrointestinal', manufacturer: 'Abbott', dosage: '1 capsule twice daily', maxDaily: '2 capsules', sideEffects: 'Diarrhea', schedule: 'With meals', color: 'White', shape: 'Capsule' },
  { name: 'Sucralfate 1g', composition: 'Sucralfate 1g', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 tablet 4 times daily', maxDaily: '4 tablets', sideEffects: 'Constipation', schedule: 'Empty stomach 1hr before meals', color: 'White', shape: 'Tablet' },
  { name: 'Mesalamine 400mg', composition: 'Mesalamine 400mg', category: 'Gastrointestinal', manufacturer: 'Sun Pharma', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Nausea, headache', schedule: 'With meals', color: 'Red', shape: 'Tablet' },
  { name: 'Piracetam 800mg', composition: 'Piracetam 800mg', category: 'Neurology', manufacturer: 'Cipla', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Nervousness, weight gain', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'Pregabalin 75mg', composition: 'Pregabalin 75mg', category: 'Neurology', manufacturer: 'Pfizer', dosage: '1 capsule twice daily', maxDaily: '2 capsules', sideEffects: 'Dizziness, drowsiness', schedule: 'With food', color: 'White', shape: 'Capsule' },
  { name: 'Pregabalin 150mg', composition: 'Pregabalin 150mg', category: 'Neurology', manufacturer: 'Pfizer', dosage: '1 capsule twice daily', maxDaily: '2 capsules', sideEffects: 'Dizziness, blurred vision', schedule: 'With food', color: 'White', shape: 'Capsule' },
  { name: 'Topiramate 25mg', composition: 'Topiramate 25mg', category: 'Neurology', manufacturer: 'Janssen', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Tingling, weight loss', schedule: 'With food', color: 'White', shape: 'Round' },
  { name: 'Sodium Valproate 200mg', composition: 'Sodium Valproate 200mg', category: 'Neurology', manufacturer: 'Sanofi', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Tremor, weight gain', schedule: 'With meals', color: 'White', shape: 'Tablet' },
  { name: 'Carbamazepine 200mg', composition: 'Carbamazepine 200mg', category: 'Neurology', manufacturer: 'Novartis', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Dizziness, rash', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'Phenytoin 100mg', composition: 'Phenytoin 100mg', category: 'Neurology', manufacturer: 'Pfizer', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Gum hyperplasia, rash', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'Levetiracetam 500mg', composition: 'Levetiracetam 500mg', category: 'Neurology', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Drowsiness, weakness', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'Levetiracetam 750mg', composition: 'Levetiracetam 750mg', category: 'Neurology', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Dizziness', schedule: 'With food', color: 'White', shape: 'Oval' },
  { name: 'Hydroxychloroquine 200mg', composition: 'Hydroxychloroquine 200mg', category: 'Immunosuppressant', manufacturer: 'Cipla', dosage: '1 tablet daily', maxDaily: '2 tablets', sideEffects: 'Nausea, vision changes', schedule: 'With food', color: 'White', shape: 'Round' },
  { name: 'Methotrexate 2.5mg', composition: 'Methotrexate 2.5mg', category: 'Immunosuppressant', manufacturer: 'Cipla', dosage: 'As directed weekly', maxDaily: 'As directed', sideEffects: 'Mouth ulcers, fatigue', schedule: 'Weekly', color: 'Yellow', shape: 'Round' },
  { name: 'Sulfasalazine 500mg', composition: 'Sulfasalazine 500mg', category: 'Immunosuppressant', manufacturer: 'Pharmacia', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Nausea, rash', schedule: 'With food', color: 'Yellow', shape: 'Tablet' },
  { name: 'Colchicine 0.5mg', composition: 'Colchicine 0.5mg', category: 'Pain Relief', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Diarrhea, nausea', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'Allopurinol 100mg', composition: 'Allopurinol 100mg', category: 'Pain Relief', manufacturer: 'GSK', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Rash, gout flare', schedule: 'After breakfast', color: 'White', shape: 'Round' },
  { name: 'Tamsulosin 0.4mg', composition: 'Tamsulosin 0.4mg', category: 'Urology', manufacturer: 'Cipla', dosage: '1 capsule daily after dinner', maxDaily: '1 capsule', sideEffects: 'Dizziness, retrograde ejaculation', schedule: '30 min after dinner', color: 'White', shape: 'Capsule' },
  { name: 'Finasteride 1mg', composition: 'Finasteride 1mg', category: 'Urology', manufacturer: 'Merck', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Decreased libido', schedule: 'With or without food', color: 'White', shape: 'Round' },
  { name: 'Finasteride 5mg', composition: 'Finasteride 5mg', category: 'Urology', manufacturer: 'Cipla', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Decreased libido', schedule: 'With or without food', color: 'White', shape: 'Round' },
  { name: 'Oxybutynin 5mg', composition: 'Oxybutynin 5mg', category: 'Urology', manufacturer: 'Cipla', dosage: '1 tablet 2-3 times daily', maxDaily: '3 tablets', sideEffects: 'Dry mouth, constipation', schedule: 'With food', color: 'White', shape: 'Round' },
  { name: 'Sildenafil 50mg', composition: 'Sildenafil 50mg', category: 'Urology', manufacturer: 'Cipla', dosage: '1 tablet 1 hour before activity', maxDaily: '1 tablet', sideEffects: 'Headache, flushing', schedule: 'As needed', color: 'Blue', shape: 'Round' },
  { name: 'Tadalafil 10mg', composition: 'Tadalafil 10mg', category: 'Urology', manufacturer: 'Eli Lilly', dosage: '1 tablet before activity', maxDaily: '1 tablet', sideEffects: 'Back pain, headache', schedule: 'As needed', color: 'White', shape: 'Oval' },
  { name: 'Ciprofloxacin 250mg', composition: 'Ciprofloxacin 250mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Nausea, tendon pain', schedule: 'Empty stomach', color: 'White', shape: 'Tablet' },
  { name: 'Ciprofloxacin 500mg', composition: 'Ciprofloxacin 500mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Nausea, diarrhea', schedule: 'Empty stomach', color: 'White', shape: 'Tablet' },
  { name: 'Levofloxacin 500mg', composition: 'Levofloxacin 500mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'Insomnia, headache', schedule: 'Empty stomach', color: 'White', shape: 'Tablet' },
  { name: 'Doxycycline 100mg', composition: 'Doxycycline 100mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 capsule twice daily', maxDaily: '2 capsules', sideEffects: 'Photosensitivity, nausea', schedule: 'With full glass of water', color: 'White', shape: 'Capsule' },
  { name: 'Clindamycin 300mg', composition: 'Clindamycin 300mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 capsule 3 times daily', maxDaily: '3 capsules', sideEffects: 'Diarrhea, metallic taste', schedule: 'With food', color: 'White', shape: 'Capsule' },
  { name: 'Minocycline 100mg', composition: 'Minocycline 100mg', category: 'Antibiotic', manufacturer: 'Sun Pharma', dosage: '1 capsule twice daily', maxDaily: '2 capsules', sideEffects: 'Dizziness, pigmentation', schedule: 'With food', color: 'White', shape: 'Capsule' },
  { name: 'Linezolid 600mg', composition: 'Linezolid 600mg', category: 'Antibiotic', manufacturer: 'Pfizer', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Diarrhea, headache', schedule: 'With or without food', color: 'White', shape: 'Tablet' },
  { name: 'Nitrofurantoin 100mg', composition: 'Nitrofurantoin 100mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 capsule 4 times daily', maxDaily: '4 capsules', sideEffects: 'Nausea, brown urine', schedule: 'With food', color: 'White', shape: 'Capsule' },
  { name: 'Metronidazole 200mg', composition: 'Metronidazole 200mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Metallic taste, nausea', schedule: 'After food', color: 'White', shape: 'Round' },
  { name: 'Metronidazole 400mg', composition: 'Metronidazole 400mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Metallic taste', schedule: 'After food', color: 'White', shape: 'Round' },
  { name: 'Tinidazole 500mg', composition: 'Tinidazole 500mg', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '1 tablet twice daily', maxDaily: '2 tablets', sideEffects: 'Metallic taste', schedule: 'After food', color: 'White', shape: 'Round' },
  { name: 'Albendazole 400mg', composition: 'Albendazole 400mg', category: 'Anti-parasitic', manufacturer: 'Cipla', dosage: '1 tablet single dose', maxDaily: '1 tablet', sideEffects: 'Abdominal pain, nausea', schedule: 'After food', color: 'White', shape: 'Tablet' },
  { name: 'Ivermectin 6mg', composition: 'Ivermectin 6mg', category: 'Anti-parasitic', manufacturer: 'Cipla', dosage: 'As directed', maxDaily: 'As directed', sideEffects: 'Dizziness, pruritus', schedule: 'Empty stomach', color: 'White', shape: 'Tablet' },
  { name: 'Diethylcarbamazine 100mg', composition: 'DEC 100mg', category: 'Anti-parasitic', manufacturer: 'Cipla', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Headache, fever', schedule: 'After food', color: 'White', shape: 'Tablet' },
  { name: 'Chloroquine 250mg', composition: 'Chloroquine 250mg', category: 'Anti-parasitic', manufacturer: 'Cipla', dosage: '1 tablet weekly for prophylaxis', maxDaily: '1 tablet', sideEffects: 'Nausea, blurred vision', schedule: 'With food', color: 'White', shape: 'Round' },
  { name: 'Artemether 40mg + Lumefantrine 240mg', composition: 'Artemether 40mg + Lumefantrine 240mg', category: 'Anti-parasitic', manufacturer: 'Cipla', dosage: '4 tablets twice daily for 3 days', maxDaily: '8 tablets', sideEffects: 'Headache, anorexia', schedule: 'With food', color: 'White', shape: 'Tablet' },
  { name: 'ORS Powder', composition: 'Oral Rehydration Salts', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 sachet per liter water', maxDaily: 'As needed', sideEffects: 'None', schedule: 'As needed', color: 'White', shape: 'Powder' },
  { name: 'Zinc 20mg (Syrup)', composition: 'Zinc Sulfate 20mg/5ml', category: 'Supplement', manufacturer: 'Cipla', dosage: '5ml daily for 14 days', maxDaily: '5ml', sideEffects: 'Metallic taste', schedule: 'After food', color: 'White', shape: 'Syrup' },
  { name: 'Multivitamin Tablet', composition: 'Multivitamins + Minerals', category: 'Supplement', manufacturer: 'Abbott', dosage: '1 tablet daily', maxDaily: '1 tablet', sideEffects: 'None', schedule: 'After breakfast', color: 'Orange', shape: 'Round' },
  { name: 'BCG Vaccine', composition: 'BCG (Bacillus Calmette-Guerin)', category: 'Vaccine', manufacturer: 'Serum Institute', dosage: '0.1ml intradermal', maxDaily: 'Single dose', sideEffects: 'Local soreness', schedule: 'At birth', color: 'White', shape: 'Vial' },
  { name: 'DPT Vaccine', composition: 'Diphtheria + Pertussis + Tetanus', category: 'Vaccine', manufacturer: 'Serum Institute', dosage: '0.5ml IM', maxDaily: 'Single dose', sideEffects: 'Fever, soreness', schedule: '6, 10, 14 weeks', color: 'White', shape: 'Vial' },
  { name: 'MMR Vaccine', composition: 'Measles + Mumps + Rubella', category: 'Vaccine', manufacturer: 'Serum Institute', dosage: '0.5ml subcutaneous', maxDaily: 'Single dose', sideEffects: 'Fever, rash', schedule: '9-12 months', color: 'White', shape: 'Vial' },
  { name: 'Hepatitis B Vaccine', composition: 'Hepatitis B surface antigen', category: 'Vaccine', manufacturer: 'Serum Institute', dosage: '0.5ml IM', maxDaily: 'Single dose', sideEffects: 'Fever, soreness', schedule: '0, 1, 6 months', color: 'White', shape: 'Vial' },
  { name: 'Influenza Vaccine', composition: 'Inactivated Influenza virus', category: 'Vaccine', manufacturer: 'Sanofi', dosage: '0.5ml IM', maxDaily: 'Annual dose', sideEffects: 'Fever, muscle aches', schedule: 'Annual', color: 'White', shape: 'Vial' },
  { name: 'COVID-19 Vaccine (Covishield)', composition: 'ChAdOx1 nCoV-19', category: 'Vaccine', manufacturer: 'Serum Institute', dosage: '0.5ml IM', maxDaily: 'Single dose', sideEffects: 'Fever, headache, fatigue', schedule: '2 doses 12-16 weeks apart', color: 'White', shape: 'Vial' },
  { name: 'COVID-19 Vaccine (Covaxin)', composition: 'Inactivated SARS-CoV-2', category: 'Vaccine', manufacturer: 'Bharat Biotech', dosage: '0.5ml IM', maxDaily: 'Single dose', sideEffects: 'Fever, headache', schedule: '2 doses 4-6 weeks apart', color: 'White', shape: 'Vial' },
  { name: 'Rabies Vaccine', composition: 'Inactivated Rabies virus', category: 'Vaccine', manufacturer: 'Sanofi', dosage: '0.5ml IM on days 0,3,7,14,28', maxDaily: 'Single dose per visit', sideEffects: 'Fever, headache', schedule: '5 doses', color: 'White', shape: 'Vial' },
  { name: 'Typhoid Vaccine', composition: 'Vi Polysaccharide', category: 'Vaccine', manufacturer: 'Sanofi', dosage: '0.5ml IM', maxDaily: 'Single dose', sideEffects: 'Fever, headache', schedule: 'Single dose, booster every 3 years', color: 'White', shape: 'Vial' },
  { name: 'Hepatitis A Vaccine', composition: 'Inactivated HAV', category: 'Vaccine', manufacturer: 'GSK', dosage: '0.5ml IM', maxDaily: 'Single dose', sideEffects: 'Fever, soreness', schedule: '2 doses 6 months apart', color: 'White', shape: 'Vial' },
  { name: 'Vitamin A Solution', composition: 'Vitamin A 50000IU', category: 'Supplement', manufacturer: 'Cipla', dosage: '1ml oral', maxDaily: '1ml', sideEffects: 'None', schedule: 'As per national schedule', color: 'White', shape: 'Liquid' },
  { name: 'ORS Apple Flavor', composition: 'Oral Rehydration Salts + Zinc', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 sachet per 200ml water', maxDaily: 'As needed', sideEffects: 'None', schedule: 'After each loose stool', color: 'White', shape: 'Powder' },
  { name: 'Dicyclomine 10mg', composition: 'Dicyclomine 10mg', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Dry mouth, blurred vision', schedule: '30 min before meals', color: 'White', shape: 'Tablet' },
  { name: 'Hyoscine 10mg', composition: 'Hyoscine Butylbromide 10mg', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'Dry mouth', schedule: 'Before meals', color: 'White', shape: 'Round' },
  { name: 'Mebeverine 135mg', composition: 'Mebeverine 135mg', category: 'Gastrointestinal', manufacturer: 'Abbott', dosage: '1 tablet 3 times daily', maxDaily: '3 tablets', sideEffects: 'None typically', schedule: '20 min before meals', color: 'White', shape: 'Tablet' },
  { name: 'Lactulose 10ml', composition: 'Lactulose 10g/15ml', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '15ml twice daily', maxDaily: '30ml', sideEffects: 'Flatulence, cramps', schedule: 'Morning and evening', color: 'White', shape: 'Liquid' },
  { name: 'Cremalax Tablet', composition: 'Bisacodyl 5mg', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1-2 tablets at bedtime', maxDaily: '2 tablets', sideEffects: 'Cramps', schedule: 'Night', color: 'White', shape: 'Tablet' },
  { name: 'Glycerin Suppository', composition: 'Glycerin 2g', category: 'Gastrointestinal', manufacturer: 'Cipla', dosage: '1 suppository as needed', maxDaily: '1 suppository', sideEffects: 'Local irritation', schedule: 'As needed', color: 'White', shape: 'Suppository' },
  { name: 'Betadine Solution', composition: 'Povidone Iodine 10%', category: 'Antiseptic', manufacturer: 'Cipla', dosage: 'Apply locally as needed', maxDaily: 'Topical', sideEffects: 'Local irritation', schedule: 'As needed', color: 'Brown', shape: 'Liquid' },
  { name: 'Soframycin Skin Cream', composition: 'Framycetin 1%', category: 'Antibiotic (Topical)', manufacturer: 'Cipla', dosage: 'Apply 2-3 times daily', maxDaily: 'Topical', sideEffects: 'Local allergy', schedule: '8 hourly', color: 'White', shape: 'Cream' },
  { name: 'Hydrocortisone Cream 1%', composition: 'Hydrocortisone 1%', category: 'Steroid (Topical)', manufacturer: 'Cipla', dosage: 'Apply thinly twice daily', maxDaily: 'Topical', sideEffects: 'Skin thinning', schedule: '12 hourly', color: 'White', shape: 'Cream' },
  { name: 'Caladryl Lotion', composition: 'Calamine + Diphenhydramine', category: 'Skin Care', manufacturer: 'Pfizer', dosage: 'Apply locally 3-4 times daily', maxDaily: 'Topical', sideEffects: 'None', schedule: 'As needed', color: 'Pink', shape: 'Lotion' },
  { name: 'Clobetasol 0.05% Cream', composition: 'Clobetasol Propionate 0.05%', category: 'Steroid (Topical)', manufacturer: 'Cipla', dosage: 'Apply thinly once daily', maxDaily: 'Topical', sideEffects: 'Skin thinning', schedule: 'Night', color: 'White', shape: 'Cream' },
  { name: 'Mometasone 0.1% Cream', composition: 'Mometasone Furoate 0.1%', category: 'Steroid (Topical)', manufacturer: 'MSD', dosage: 'Apply once daily', maxDaily: 'Topical', sideEffects: 'Local burning', schedule: 'Daily', color: 'White', shape: 'Cream' },
  { name: 'Silver Sulfadiazine 1% Cream', composition: 'Silver Sulfadiazine 1%', category: 'Burns', manufacturer: 'Cipla', dosage: 'Apply once/twice daily', maxDaily: 'Topical', sideEffects: 'Local burning', schedule: 'As directed', color: 'White', shape: 'Cream' },
  { name: 'Neosporin Ointment', composition: 'Neomycin + Bacitracin + Polymyxin', category: 'Antibiotic (Topical)', manufacturer: 'GSK', dosage: 'Apply 2-3 times daily', maxDaily: 'Topical', sideEffects: 'Local allergy', schedule: 'As needed', color: 'White', shape: 'Ointment' },
  { name: 'Eye Drop (Moxifloxacin 0.5%)', composition: 'Moxifloxacin 0.5%', category: 'Eye', manufacturer: 'Cipla', dosage: '1 drop 4 times daily', maxDaily: '1 drop per dose', sideEffects: 'Local burning', schedule: '6 hourly', color: 'White', shape: 'Eye Drop' },
  { name: 'Eye Drop (Tobramycin 0.3%)', composition: 'Tobramycin 0.3%', category: 'Eye', manufacturer: 'Cipla', dosage: '1 drop 4 times daily', maxDaily: '1 drop per dose', sideEffects: 'Local irritation', schedule: '6 hourly', color: 'White', shape: 'Eye Drop' },
  { name: 'Eye Drop (Timolol 0.5%)', composition: 'Timolol Maleate 0.5%', category: 'Eye (Glaucoma)', manufacturer: 'Cipla', dosage: '1 drop twice daily', maxDaily: '1 drop per dose', sideEffects: 'Burning, blurred vision', schedule: '12 hourly', color: 'White', shape: 'Eye Drop' },
  { name: 'Eye Drop (Latanoprost 0.005%)', composition: 'Latanoprost 0.005%', category: 'Eye (Glaucoma)', manufacturer: 'Cipla', dosage: '1 drop at night', maxDaily: '1 drop', sideEffects: 'Eye color change, lashes', schedule: 'Night', color: 'White', shape: 'Eye Drop' },
  { name: 'Artificial Tears', composition: 'Carboxymethylcellulose 0.5%', category: 'Eye', manufacturer: 'Cipla', dosage: '1 drop as needed', maxDaily: 'As needed', sideEffects: 'None', schedule: 'As needed', color: 'White', shape: 'Eye Drop' },
  { name: 'Eye Ointment (Chloramphenicol 1%)', composition: 'Chloramphenicol 1%', category: 'Eye', manufacturer: 'Cipla', dosage: 'Apply 3-4 times daily', maxDaily: 'Topical', sideEffects: 'Local allergy', schedule: '6 hourly', color: 'White', shape: 'Ointment' },
  { name: 'Nasal Spray (Fluticasone)', composition: 'Fluticasone Propionate 50mcg', category: 'Respiratory', manufacturer: 'GSK', dosage: '2 sprays each nostril twice daily', maxDaily: '4 sprays per nostril', sideEffects: 'Nosebleed, headache', schedule: '12 hourly', color: 'White', shape: 'Nasal Spray' },
  { name: 'Nasal Spray (Saline)', composition: 'Sodium Chloride 0.65%', category: 'Respiratory', manufacturer: 'Cipla', dosage: '2 sprays each nostril as needed', maxDaily: 'As needed', sideEffects: 'None', schedule: 'As needed', color: 'White', shape: 'Nasal Spray' },
  { name: 'Cetirizine Syrup', composition: 'Cetirizine 5mg/5ml', category: 'Allergy', manufacturer: 'Cipla', dosage: '5ml daily', maxDaily: '5ml', sideEffects: 'Drowsiness', schedule: 'Night', color: 'White', shape: 'Syrup' },
  { name: 'Paracetamol Syrup (Pedicare)', composition: 'Paracetamol 125mg/5ml', category: 'Pain Relief', manufacturer: 'Cipla', dosage: '5ml 3-4 times daily', maxDaily: '20ml', sideEffects: 'None at recommended dose', schedule: '6 hourly', color: 'White', shape: 'Syrup' },
  { name: 'Ibuprofen Syrup', composition: 'Ibuprofen 100mg/5ml', category: 'Pain Relief', manufacturer: 'Cipla', dosage: '5ml 3 times daily', maxDaily: '15ml', sideEffects: 'GI upset', schedule: 'After food', color: 'White', shape: 'Syrup' },
  { name: 'Amoxicillin Syrup', composition: 'Amoxicillin 125mg/5ml', category: 'Antibiotic', manufacturer: 'Cipla', dosage: '5ml 3 times daily', maxDaily: '15ml', sideEffects: 'Diarrhea, rash', schedule: 'After food', color: 'White', shape: 'Syrup' },
  { name: 'Iron Syrup', composition: 'Ferrous Sulfate 30mg/5ml', category: 'Supplement', manufacturer: 'Cipla', dosage: '5ml twice daily', maxDaily: '10ml', sideEffects: 'Constipation, dark stools', schedule: 'After food', color: 'White', shape: 'Syrup' },
];

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const search = searchParams.get('search') || '';
  const category = searchParams.get('category') || '';
  
  try {
    let results = MEDICINE_DATABASE;
    
    if (search) {
      const term = search.toLowerCase();
      results = results.filter(p => 
        p.name.toLowerCase().includes(term) ||
        p.category.toLowerCase().includes(term) ||
        p.composition.toLowerCase().includes(term) ||
        p.manufacturer.toLowerCase().includes(term)
      );
    }
    
    if (category) {
      results = results.filter(p => p.category.toLowerCase() === category.toLowerCase());
    }
    
    const categories = [...new Set(MEDICINE_DATABASE.map(m => m.category))];
    
    return NextResponse.json({ success: true, medicines: results, total: results.length, categories });
  } catch (error) {
    return NextResponse.json({ error: 'Failed to search medicines' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  const token = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
  
  try {
    const body = await req.json();
    const matchedMedicines = body.medicineName
      ? MEDICINE_DATABASE.filter(m => m.name.toLowerCase().includes(body.medicineName.toLowerCase()))
      : [];
    
    const record = await prisma.pillRecord.create({
      data: {
        userId: token?.id as string || null,
        imageData: body.imageData || null,
        pillName: body.medicineName || matchedMedicines[0]?.name || null,
        description: matchedMedicines[0]?.composition ? `Composition: ${matchedMedicines[0].composition}` : null,
        dosage: matchedMedicines[0]?.dosage || null,
        matches: matchedMedicines.length > 0 ? JSON.stringify(matchedMedicines) : null,
      },
    });
    
    return NextResponse.json({ success: true, record, matches: matchedMedicines });
  } catch (error) {
    return NextResponse.json({ error: 'Invalid request' }, { status: 400 });
  }
}
