'use client';
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

const translations: Record<string, Record<string, string>> = {
  en: {
    home: 'Home', hospitals: 'Hospitals', specialists: 'Specialists', healthCamps: 'Health Camps',
    emergency: 'Emergency', myHealth: 'My Health', premium: 'Premium', helpline: 'Helpline',
    signIn: 'Sign In', logout: 'Logout', findHospitals: 'Find Hospitals', findSpecialists: 'Find Specialists',
    heroTitle: 'Your Health, Our', heroPriority: 'Priority',
    heroDesc: 'Find the best hospitals, specialists, and healthcare services across India. Book appointments instantly.',
    search: 'Search', allSpecialties: 'All Specialties', allLocations: 'All Locations', allStates: 'All States',
    filters: 'Filters', emergencyOnly: 'Emergency Services Only', hospitalsFound: 'hospitals found',
    doctorsFound: 'doctors found', viewAll: 'View All', viewDetails: 'View Details',
    bookAppointment: 'Book Appointment', registerNow: 'Register Now', availableToday: 'Available Today',
    bedsAvailable: 'Beds Available', icuFree: 'ICU Free', bedOccupancy: 'Bed Occupancy',
    emergencyNumbers: 'Emergency Numbers', quickAccess: 'Quick access to emergency services across India',
    ambulance: 'Ambulance', police: 'Police', fire: 'Fire',
    topHospitals: 'Top Hospitals', topSpecialists: 'Top Specialists', ourSpecialties: 'Our Specialties',
    upcomingCamps: 'Upcoming Health Camps', downloadApp: 'Download Our Mobile App',
    choosePlan: 'Choose Your Plan', currentPlan: 'Current Plan', subscribeNow: 'Subscribe Now',
    loading: 'Loading...', noResults: 'No results found', clearFilters: 'Clear filters',
    language: 'Language', searchPlaceholder: 'Search doctors, hospitals, conditions...',
    verifiedHospitals: 'Verified Hospitals', expertDoctors: 'Expert Doctors',
    happyPatients: 'Happy Patients', yearsService: 'Years of Service',
    needEmergencyHelp: 'Need Emergency Help?', emergencyDesc: 'Our 24/7 emergency services are always ready to help you.',
    findNearest: 'Find Nearest Hospital', campsFree: 'Free health checkups and screenings near you',
    chatAssistant: 'Health Assistant', chatOnline: 'Online • Ready to help',
    chatPlaceholder: 'Type your message...', quickActions: 'Quick actions:',
    findNearestHospital: 'Find nearest hospital', bookAppointmentAction: 'Book appointment',
    emergencyHelp: 'Emergency help', findSpecialist: 'Find specialist',
    healthTips: 'Health tips', medicinesInfo: 'Medicines info',
    emergencyCallTitle: '🚨 Emergency Check',
    emergencyCallDesc: 'You have been browsing for a while. Are you looking for emergency medical help?',
    yesEmergency: 'Yes, I need help!', noEmergency: 'No, I\'m fine',
    connectingHospital: 'Connecting you to the nearest hospital...',
    aiSpeaking: 'AI Assistant is speaking...',
    legal: 'Legal',
    contact: 'Contact',
    saasBuilder: 'SaaS Builder',
  },
  hi: {
    home: 'होम', hospitals: 'अस्पताल', specialists: 'विशेषज्ञ', healthCamps: 'स्वास्थ्य शिविर',
    emergency: 'आपातकाल', myHealth: 'मेरा स्वास्थ्य', premium: 'प्रीमियम', helpline: 'हेल्पलाइन',
    signIn: 'साइन इन', logout: 'लॉगआउट', findHospitals: 'अस्पताल खोजें', findSpecialists: 'विशेषज्ञ खोजें',
    heroTitle: 'आपका स्वास्थ्य, हमारी', heroPriority: 'प्राथमिकता',
    heroDesc: 'भारत भर में सबसे अच्छे अस्पतालों, विशेषज्ञों और स्वास्थ्य सेवाओं को खोजें।',
    search: 'खोजें', allSpecialties: 'सभी विशेषताएं', allLocations: 'सभी स्थान', allStates: 'सभी राज्य',
    filters: 'फ़िल्टर', emergencyOnly: 'केवल आपातकालीन सेवाएं', hospitalsFound: 'अस्पताल मिले',
    doctorsFound: 'डॉक्टर मिले', viewAll: 'सभी देखें', viewDetails: 'विवरण देखें',
    bookAppointment: 'अपॉइंटमेंट बुक करें', registerNow: 'अभी रजिस्टर करें', availableToday: 'आज उपलब्ध',
    bedsAvailable: 'बेड उपलब्ध', icuFree: 'ICU खाली', bedOccupancy: 'बेड अधिभोग',
    emergencyNumbers: 'आपातकालीन नंबर', quickAccess: 'भारत भर में आपातकालीन सेवाओं तक त्वरित पहुंच',
    ambulance: 'एम्बुलेंस', police: 'पुलिस', fire: 'अग्निशमन',
    topHospitals: 'शीर्ष अस्पताल', topSpecialists: 'शीर्ष विशेषज्ञ', ourSpecialties: 'हमारी विशेषताएं',
    upcomingCamps: 'आगामी स्वास्थ्य शिविर', downloadApp: 'हमारा मोबाइल ऐप डाउनलोड करें',
    choosePlan: 'अपना प्लान चुनें', currentPlan: 'वर्तमान प्लान', subscribeNow: 'अभी सब्सक्राइब करें',
    loading: 'लोड हो रहा है...', noResults: 'कोई परिणाम नहीं', clearFilters: 'फ़िल्टर साफ़ करें',
    language: 'भाषा', searchPlaceholder: 'डॉक्टर, अस्पताल, बीमारी खोजें...',
    verifiedHospitals: 'सत्यापित अस्पताल', expertDoctors: 'विशेषज्ञ डॉक्टर',
    happyPatients: 'खुश मरीज़', yearsService: 'सेवा के वर्ष',
    needEmergencyHelp: 'आपातकालीन मदद चाहिए?', emergencyDesc: 'हमारी 24/7 आपातकालीन सेवाएं हमेशा तैयार हैं।',
    findNearest: 'नज़दीकी अस्पताल खोजें', campsFree: 'आपके पास मुफ्त स्वास्थ्य जांच शिविर',
    chatAssistant: 'स्वास्थ्य सहायक', chatOnline: 'ऑनलाइन • मदद के लिए तैयार',
    chatPlaceholder: 'अपना संदेश लिखें...', quickActions: 'त्वरित कार्य:',
    findNearestHospital: 'नज़दीकी अस्पताल खोजें', bookAppointmentAction: 'अपॉइंटमेंट बुक करें',
    emergencyHelp: 'आपातकालीन मदद', findSpecialist: 'विशेषज्ञ खोजें',
    healthTips: 'स्वास्थ्य सुझाव', medicinesInfo: 'दवाई जानकारी',
    emergencyCallTitle: '🚨 आपातकालीन जांच',
    emergencyCallDesc: 'आप काफी देर से ब्राउज़ कर रहे हैं। क्या आपको आपातकालीन चिकित्सा सहायता चाहिए?',
    yesEmergency: 'हां, मुझे मदद चाहिए!', noEmergency: 'नहीं, मैं ठीक हूं',
    connectingHospital: 'आपको नज़दीकी अस्पताल से जोड़ रहे हैं...',
    aiSpeaking: 'AI सहायक बोल रहा है...',
    legal: 'कानूनी',
    contact: 'संपर्क',
    saasBuilder: 'SaaS बिल्डर',
  },
  kn: {
    home: 'ಮುಖಪುಟ', hospitals: 'ಆಸ್ಪತ್ರೆಗಳು', specialists: 'ತಜ್ಞರು', healthCamps: 'ಆರೋಗ್ಯ ಶಿಬಿರಗಳು',
    emergency: 'ತುರ್ತು', myHealth: 'ನನ್ನ ಆರೋಗ್ಯ', premium: 'ಪ್ರೀಮಿಯಂ', helpline: 'ಸಹಾಯವಾಣಿ',
    signIn: 'ಲಾಗಿನ್', logout: 'ಲಾಗ್ಔಟ್', findHospitals: 'ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ', findSpecialists: 'ತಜ್ಞರನ್ನು ಹುಡುಕಿ',
    heroTitle: 'ನಿಮ್ಮ ಆರೋಗ್ಯ, ನಮ್ಮ', heroPriority: 'ಆದ್ಯತೆ',
    heroDesc: 'ಭಾರತದಾದ್ಯಂತ ಅತ್ಯುತ್ತಮ ಆಸ್ಪತ್ರೆಗಳು ಮತ್ತು ತಜ್ಞರನ್ನು ಹುಡುಕಿ.',
    search: 'ಹುಡುಕಿ', allSpecialties: 'ಎಲ್ಲಾ ತಜ್ಞತೆಗಳು', allLocations: 'ಎಲ್ಲಾ ಸ್ಥಳಗಳು', allStates: 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು',
    filters: 'ಫಿಲ್ಟರ್‌ಗಳು', emergencyOnly: 'ತುರ್ತು ಸೇವೆಗಳು ಮಾತ್ರ', hospitalsFound: 'ಆಸ್ಪತ್ರೆಗಳು ಸಿಕ್ಕಿವೆ',
    doctorsFound: 'ವೈದ್ಯರು ಸಿಕ್ಕಿದ್ದಾರೆ', viewAll: 'ಎಲ್ಲಾ ನೋಡಿ', viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ', registerNow: 'ಈಗ ನೋಂದಾಯಿಸಿ', availableToday: 'ಇಂದು ಲಭ್ಯ',
    bedsAvailable: 'ಹಾಸಿಗೆಗಳು ಲಭ್ಯ', icuFree: 'ICU ಖಾಲಿ', bedOccupancy: 'ಹಾಸಿಗೆ ಭರ್ತಿ',
    emergencyNumbers: 'ತುರ್ತು ಸಂಖ್ಯೆಗಳು', quickAccess: 'ಭಾರತದಾದ್ಯಂತ ತುರ್ತು ಸೇವೆಗಳಿಗೆ ತ್ವರಿತ ಪ್ರವೇಶ',
    ambulance: 'ಆಂಬ್ಯುಲೆನ್ಸ್', police: 'ಪೊಲೀಸ್', fire: 'ಅಗ್ನಿಶಾಮಕ',
    topHospitals: 'ಉನ್ನತ ಆಸ್ಪತ್ರೆಗಳು', topSpecialists: 'ಉನ್ನತ ತಜ್ಞರು', ourSpecialties: 'ನಮ್ಮ ತಜ್ಞತೆಗಳು',
    upcomingCamps: 'ಮುಂಬರುವ ಆರೋಗ್ಯ ಶಿಬಿರಗಳು', downloadApp: 'ನಮ್ಮ ಮೊಬೈಲ್ ಆ್ಯಪ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    choosePlan: 'ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ಆರಿಸಿ', currentPlan: 'ಪ್ರಸ್ತುತ ಯೋಜನೆ', subscribeNow: 'ಈಗ ಚಂದಾದಾರರಾಗಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', noResults: 'ಯಾವುದೇ ಫಲಿತಾಂಶ ಸಿಗಲಿಲ್ಲ', clearFilters: 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
    language: 'ಭಾಷೆ', searchPlaceholder: 'ವೈದ್ಯರು, ಆಸ್ಪತ್ರೆಗಳು, ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಹುಡುಕಿ...',
    verifiedHospitals: 'ಪರಿಶೀಲಿಸಿದ ಆಸ್ಪತ್ರೆಗಳು', expertDoctors: 'ಪರಿಣಿತ ವೈದ್ಯರು',
    happyPatients: 'ಸಂತೋಷದ ರೋಗಿಗಳು', yearsService: 'ಸೇವೆಯ ವರ್ಷಗಳು',
    needEmergencyHelp: 'ತುರ್ತು ಸಹಾಯ ಬೇಕೇ?', emergencyDesc: 'ನಮ್ಮ 24/7 ತುರ್ತು ಸೇವೆಗಳು ಯಾವಾಗಲೂ ಸಿದ್ಧವಾಗಿವೆ.',
    findNearest: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ', campsFree: 'ನಿಮ್ಮ ಹತ್ತಿರ ಉಚಿತ ಆರೋಗ್ಯ ತಪಾಸಣೆ ಶಿಬಿರಗಳು',
    chatAssistant: 'ಆರೋಗ್ಯ ಸಹಾಯಕ', chatOnline: 'ಆನ್‌ಲೈನ್ • ಸಹಾಯಕ್ಕೆ ಸಿದ್ಧ',
    chatPlaceholder: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...', quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು:',
    findNearestHospital: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ', bookAppointmentAction: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
    emergencyHelp: 'ತುರ್ತು ಸಹಾಯ', findSpecialist: 'ತಜ್ಞರನ್ನು ಹುಡುಕಿ',
    healthTips: 'ಆರೋಗ್ಯ ಸಲಹೆಗಳು', medicinesInfo: 'ಔಷಧ ಮಾಹಿತಿ',
    emergencyCallTitle: '🚨 ತುರ್ತು ಪರಿಶೀಲನೆ',
    emergencyCallDesc: 'ನೀವು ಸ್ವಲ್ಪ ಹೊತ್ತಿನಿಂದ ಬ್ರೌಸ್ ಮಾಡುತ್ತಿದ್ದೀರಿ. ನಿಮಗೆ ತುರ್ತು ವೈದ್ಯಕೀಯ ಸಹಾಯ ಬೇಕೇ?',
    yesEmergency: 'ಹೌದು, ನನಗೆ ಸಹಾಯ ಬೇಕು!', noEmergency: 'ಇಲ್ಲ, ನಾನು ಚೆನ್ನಾಗಿದ್ದೇನೆ',
    connectingHospital: 'ನಿಮ್ಮನ್ನು ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗೆ ಸಂಪರ್ಕಿಸುತ್ತಿದ್ದೇವೆ...',
    aiSpeaking: 'AI ಸಹಾಯಕ ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ...',
    legal: 'ಕಾನೂನು',
    contact: 'ಸಂಪರ್ಕ',
    saasBuilder: 'SaaS ಬಿಲ್ಡರ್',
  },
  ml: {
    home: 'ഹോം', hospitals: 'ആശുപത്രികൾ', specialists: 'വിദഗ്ധർ', healthCamps: 'ആരോഗ്യ ക്യാമ്പുകൾ',
    emergency: 'അടിയന്തരം', myHealth: 'എൻ്റെ ആരോഗ്യം', premium: 'പ്രീമിയം', helpline: 'ഹെൽപ്പ്‌ലൈൻ',
    signIn: 'ലോഗിൻ', logout: 'ലോഗ് ഔട്ട്', findHospitals: 'ആശുപത്രികൾ കണ്ടെത്തുക', findSpecialists: 'വിദഗ്ധരെ കണ്ടെത്തുക',
    heroTitle: 'നിങ്ങളുടെ ആരോഗ്യം, ഞങ്ങളുടെ', heroPriority: 'മുൻഗണന',
    heroDesc: 'ഇന്ത്യയിലെ മികച്ച ആശുപത്രികളും വിദഗ്ധരും കണ്ടെത്തുക.',
    search: 'തിരയുക', allSpecialties: 'എല്ലാ വിദഗ്ധതകളും', allLocations: 'എല്ലാ സ്ഥലങ്ങളും', allStates: 'എല്ലാ സംസ്ഥാനങ്ങളും',
    filters: 'ഫിൽട്ടറുകൾ', emergencyOnly: 'അടിയന്തര സേവനങ്ങൾ മാത്രം', hospitalsFound: 'ആശുപത്രികൾ കണ്ടെത്തി',
    doctorsFound: 'ഡോക്ടർമാരെ കണ്ടെത്തി', viewAll: 'എല്ലാം കാണുക', viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    bookAppointment: 'അപ്പോയിൻ്റ്മെൻ്റ് ബുക്ക് ചെയ്യുക', registerNow: 'ഇപ്പോൾ രജിസ്റ്റർ ചെയ്യുക', availableToday: 'ഇന്ന് ലഭ്യം',
    bedsAvailable: 'കിടക്കകൾ ലഭ്യം', icuFree: 'ICU ഒഴിഞ്ഞത്', bedOccupancy: 'കിടക്ക തികച്ചുക',
    emergencyNumbers: 'അടിയന്തര നമ്പറുകൾ', quickAccess: 'ഇന്ത്യ മുഴുവനുമുള്ള അടിയന്തര സേവനങ്ങളിലേക്ക് ദ്രുത പ്രവേശനം',
    ambulance: 'ആംബുലൻസ്', police: 'പോലീസ്', fire: 'അഗ്നിശമനം',
    topHospitals: 'മികച്ച ആശുപത്രികൾ', topSpecialists: 'മികച്ച വിദഗ്ധർ', ourSpecialties: 'ഞങ്ങളുടെ വിദഗ്ധതകൾ',
    upcomingCamps: 'വരാനിരിക്കുന്ന ആരോഗ്യ ക്യാമ്പുകൾ', downloadApp: 'ഞങ്ങളുടെ മൊബൈൽ ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക',
    choosePlan: 'നിങ്ങളുടെ പ്ലാൻ തിരഞ്ഞെടുക്കുക', currentPlan: 'നിലവിലെ പ്ലാൻ', subscribeNow: 'ഇപ്പോൾ സബ്സ്ക്രൈബ് ചെയ്യുക',
    loading: 'ലോഡ് ചെയ്യുന്നു...', noResults: 'ഫലങ്ങൾ ഒന്നും കണ്ടെത്തിയില്ല', clearFilters: 'ഫിൽട്ടറുകൾ മായ്ക്കുക',
    language: 'ഭാഷ', searchPlaceholder: 'ഡോക്ടർമാരെ, ആശുപത്രികൾ, അവസ്ഥകൾ തിരയുക...',
    verifiedHospitals: 'സ്ഥിരീകരിച്ച ആശുപത്രികൾ', expertDoctors: 'വിദഗ്ധ ഡോക്ടർമാർ',
    happyPatients: 'സന്തുഷ്ട രോഗികൾ', yearsService: 'സേവന വർഷങ്ങൾ',
    needEmergencyHelp: 'അടിയന്തര സഹായം വേണോ?', emergencyDesc: 'ഞങ്ങളുടെ 24/7 അടിയന്തര സേവനങ്ങൾ എപ്പോഴും സജ്ജമാണ്.',
    findNearest: 'അടുത്തുള്ള ആശുപത്രി കണ്ടെത്തുക', campsFree: 'നിങ്ങൾക്ക് സൗജന്യ ആരോഗ്യ പരിശോധന ക്യാമ്പുകൾ',
    chatAssistant: 'ആരോഗ്യ സഹായി', chatOnline: 'ഓൺലൈൻ • സഹായത്തിന് സജ്ജം',
    chatPlaceholder: 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...', quickActions: 'ദ്രുത പ്രവർത്തനങ്ങൾ:',
    findNearestHospital: 'അടുത്തുള്ള ആശുപത്രി കണ്ടെത്തുക', bookAppointmentAction: 'അപ്പോയിൻ്റ്മെൻ്റ് ബുക്ക് ചെയ്യുക',
    emergencyHelp: 'അടിയന്തര സഹായം', findSpecialist: 'വിദഗ്ധരെ കണ്ടെത്തുക',
    healthTips: 'ആരോഗ്യ നുറുങ്ങുകൾ', medicinesInfo: 'മരുന്ന് വിവരം',
    emergencyCallTitle: '🚨 അടിയന്തര പരിശോധന',
    emergencyCallDesc: 'നിങ്ങൾ കുറച്ച് നേരമായി ബ്രൗസ് ചെയ്യുന്നു. നിങ്ങൾക്ക് അടിയന്തര വൈദ്യസഹായം വേണോ?',
    yesEmergency: 'അതെ, എനിക്ക് സഹായം വേണം!', noEmergency: 'ഇല്ല, ഞാൻ ശരിയാണ്',
    connectingHospital: 'നിങ്ങളെ അടുത്തുള്ള ആശുപത്രിയിലേക്ക് കണക്റ്റ് ചെയ്യുന്നു...',
    aiSpeaking: 'AI സഹായി സംസാരിക്കുന്നു...',
    legal: 'നിയമപരം',
    contact: 'ബന്ധപ്പെടുക',
    saasBuilder: 'SaaS ബിൽഡർ',
  },
  pa: {
    home: 'ਹੋਮ', hospitals: 'ਹਸਪਤਾਲ', specialists: 'ਮਾਹਿਰ', healthCamps: 'ਸਿਹਤ ਕੈਂਪ',
    emergency: 'ਐਮਰਜੈਂਸੀ', myHealth: 'ਮੇਰੀ ਸਿਹਤ', premium: 'ਪ੍ਰੀਮੀਅਮ', helpline: 'ਹੈਲਪਲਾਈਨ',
    signIn: 'ਲੌਗਿਨ', logout: 'ਲੌਗਆਊਟ', findHospitals: 'ਹਸਪਤਾਲ ਲੱਭੋ', findSpecialists: 'ਮਾਹਿਰ ਲੱਭੋ',
    heroTitle: 'ਤੁਹਾਡੀ ਸਿਹਤ, ਸਾਡੀ', heroPriority: 'ਤਰਜੀਹ',
    heroDesc: 'ਭਾਰਤ ਭਰ ਵਿੱਚ ਸਭ ਤੋਂ ਵਧੀਆ ਹਸਪਤਾਲ ਅਤੇ ਮਾਹਿਰ ਲੱਭੋ।',
    search: 'ਖੋਜੋ', allSpecialties: 'ਸਾਰੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ', allLocations: 'ਸਾਰੇ ਸਥਾਨ', allStates: 'ਸਾਰੇ ਰਾਜ',
    filters: 'ਫ਼ਿਲਟਰ', emergencyOnly: 'ਸਿਰਫ਼ ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ', hospitalsFound: 'ਹਸਪਤਾਲ ਮਿਲੇ',
    doctorsFound: 'ਡਾਕਟਰ ਮਿਲੇ', viewAll: 'ਸਭ ਵੇਖੋ', viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    bookAppointment: 'ਅਪਾਇਂਟਮੈਂਟ ਬੁੱਕ ਕਰੋ', registerNow: 'ਹੁਣੇ ਰਜਿਸਟਰ ਕਰੋ', availableToday: 'ਅੱਜ ਉਪਲਬਧ',
    bedsAvailable: 'ਬੈੱਡ ਉਪਲਬਧ', icuFree: 'ICU ਖਾਲੀ', bedOccupancy: 'ਬੈੱਡ ਭਰਤੀ',
    emergencyNumbers: 'ਐਮਰਜੈਂਸੀ ਨੰਬਰ', quickAccess: 'ਭਾਰਤ ਭਰ ਵਿੱਚ ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ ਤੱਕ ਤੇਜ਼ ਪਹੁੰਚ',
    ambulance: 'ਐਂਬੂਲੈਂਸ', police: 'ਪੁਲਿਸ', fire: 'ਅੱਗ',
    topHospitals: 'ਉੱਚ ਹਸਪਤਾਲ', topSpecialists: 'ਉੱਚ ਮਾਹਿਰ', ourSpecialties: 'ਸਾਡੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    upcomingCamps: 'ਆਉਣ ਵਾਲੇ ਸਿਹਤ ਕੈਂਪ', downloadApp: 'ਸਾਡੀ ਮੋਬਾਈਲ ਐਪ ਡਾਊਨਲੋਡ ਕਰੋ',
    choosePlan: 'ਆਪਣੀ ਯੋਜਨਾ ਚੁਣੋ', currentPlan: 'ਮੌਜੂਦਾ ਯੋਜਨਾ', subscribeNow: 'ਹੁਣੇ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', noResults: 'ਕੋਈ ਨਤੀਜੇ ਨਹੀਂ ਮਿਲੇ', clearFilters: 'ਫ਼ਿਲਟਰ ਸਾਫ਼ ਕਰੋ',
    language: 'ਭਾਸ਼ਾ', searchPlaceholder: 'ਡਾਕਟਰ, ਹਸਪਤਾਲ, ਹਾਲਤਾਂ ਖੋਜੋ...',
    verifiedHospitals: 'ਪ੍ਰਮਾਣਿਤ ਹਸਪਤਾਲ', expertDoctors: 'ਮਾਹਿਰ ਡਾਕਟਰ',
    happyPatients: 'ਖੁਸ਼ ਮਰੀਜ਼', yearsService: 'ਸੇਵਾ ਦੇ ਸਾਲ',
    needEmergencyHelp: 'ਐਮਰਜੈਂਸੀ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?', emergencyDesc: 'ਸਾਡੀਆਂ 24/7 ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ ਹਮੇਸ਼ਾ ਤਿਆਰ ਹਨ।',
    findNearest: 'ਨੇੜੇ ਦਾ ਹਸਪਤਾਲ ਲੱਭੋ', campsFree: 'ਤੁਹਾਡੇ ਨੇੜੇ ਮੁਫ਼ਤ ਸਿਹਤ ਜਾਂਚ ਕੈਂਪ',
    chatAssistant: 'ਸਿਹਤ ਸਹਾਇਕ', chatOnline: 'ਆਨਲਾਈਨ • ਮਦਦ ਲਈ ਤਿਆਰ',
    chatPlaceholder: 'ਆਪਣਾ ਸੁਨੇਹਾ ਲਿਖੋ...', quickActions: 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ:',
    findNearestHospital: 'ਨੇੜੇ ਦਾ ਹਸਪਤਾਲ ਲੱਭੋ', bookAppointmentAction: 'ਅਪਾਇਂਟਮੈਂਟ ਬੁੱਕ ਕਰੋ',
    emergencyHelp: 'ਐਮਰਜੈਂਸੀ ਮਦਦ', findSpecialist: 'ਮਾਹਿਰ ਲੱਭੋ',
    healthTips: 'ਸਿਹਤ ਸੁਝਾਅ', medicinesInfo: 'ਦਵਾਈ ਜਾਣਕਾਰੀ',
    emergencyCallTitle: '🚨 ਐਮਰਜੈਂਸੀ ਜਾਂਚ',
    emergencyCallDesc: 'ਤੁਸੀਂ ਕਾਫ਼ੀ ਦੇਰ ਤੋਂ ਬ੍ਰਾਊਜ਼ ਕਰ ਰਹੇ ਹੋ। ਕੀ ਤੁਹਾਨੂੰ ਐਮਰਜੈਂਸੀ ਡਾਕਟਰੀ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    yesEmergency: 'ਹਾਂ, ਮੈਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ!', noEmergency: 'ਨਹੀਂ, ਮੈਂ ਠੀਕ ਹਾਂ',
    connectingHospital: 'ਤੁਹਾਨੂੰ ਨੇੜੇ ਦੇ ਹਸਪਤਾਲ ਨਾਲ ਜੋੜ ਰਹੇ ਹਾਂ...',
    aiSpeaking: 'AI ਸਹਾਇਕ ਬੋਲ ਰਿਹਾ ਹੈ...',
    legal: 'ਕਾਨੂੰਨੀ',
    contact: 'ਸੰਪਰਕ',
    saasBuilder: 'SaaS ਬਿਲਡਰ',
  },
  bn: {
    home: 'হোম', hospitals: 'হাসপাতাল', specialists: 'বিশেষজ্ঞ', healthCamps: 'স্বাস্থ্য শিবির',
    emergency: 'জরুরি', myHealth: 'আমার স্বাস্থ্য', premium: 'প্রিমিয়াম', helpline: 'হেল্পলাইন',
    signIn: 'সাইন ইন', logout: 'লগআউট', findHospitals: 'হাসপাতাল খুঁজুন', findSpecialists: 'বিশেষজ্ঞ খুঁজুন',
    heroTitle: 'আপনার স্বাস্থ্য, আমাদের', heroPriority: 'অগ্রাধিকার',
    heroDesc: 'ভারত জুড়ে সেরা হাসপাতাল ও বিশেষজ্ঞদের খুঁজুন।',
    search: 'খুঁজুন', filters: 'ফিল্টার', loading: 'লোড হচ্ছে...', language: 'ভাষা',
    emergencyCallTitle: '🚨 জরুরি পরীক্ষা',
    emergencyCallDesc: 'আপনি অনেকক্ষণ ধরে ব্রাউজ করছেন। আপনার কি জরুরি চিকিৎসা সাহায্য দরকার?',
    yesEmergency: 'হ্যাঁ, আমার সাহায্য দরকার!', noEmergency: 'না, আমি ঠিক আছি',
  },
  ta: {
    home: 'முகப்பு', hospitals: 'மருத்துவமனைகள்', specialists: 'நிபுணர்கள்', emergency: 'அவசரம்',
    signIn: 'உள்நுழைக', search: 'தேடு', language: 'மொழி', loading: 'ஏற்றுகிறது...',
    emergencyCallTitle: '🚨 அவசர சோதனை',
    yesEmergency: 'ஆம், எனக்கு உதவி தேவை!', noEmergency: 'இல்லை, நான் நன்றாக இருக்கிறேன்',
  },
  te: {
    home: 'హోమ్', hospitals: 'ఆసుపత్రులు', specialists: 'నిపుణులు', emergency: 'అత్యవసరం',
    signIn: 'సైన్ ఇన్', search: 'వెతకండి', language: 'భాష', loading: 'లోడ్ అవుతోంది...',
    emergencyCallTitle: '🚨 అత్యవసర తనిఖీ',
    yesEmergency: 'అవును, నాకు సహాయం కావాలి!', noEmergency: 'లేదు, నేను బాగానే ఉన్నాను',
  },
  mr: {
    home: 'होम', hospitals: 'रुग्णालये', specialists: 'तज्ञ', emergency: 'आणीबाणी',
    signIn: 'साइन इन', search: 'शोधा', language: 'भाषा', loading: 'लोड होत आहे...',
    emergencyCallTitle: '🚨 आणीबाणी तपासणी',
    yesEmergency: 'हो, मला मदत हवी आहे!', noEmergency: 'नाही, मी ठीक आहे',
  },
  hinglish: {
    home: 'Home', hospitals: 'Hospitals', specialists: 'Doctors', healthCamps: 'Health Camps',
    emergency: 'Emergency', myHealth: 'Meri Health', premium: 'Premium', helpline: 'Helpline',
    signIn: 'Login Karo', logout: 'Logout', findHospitals: 'Hospital Dhundo', findSpecialists: 'Doctor Dhundo',
    heroTitle: 'Aapki Health, Humari', heroPriority: 'Zimmedari',
    heroDesc: 'India bhar ke best hospitals aur doctors ki jankari ek hi jagah. Abhi appointment book karo!',
    search: 'Search Karo', allSpecialties: 'Sab Specialties', allLocations: 'Sab Jagah', allStates: 'Sab States',
    filters: 'Filters', emergencyOnly: 'Sirf Emergency Services', hospitalsFound: 'hospital mile',
    doctorsFound: 'doctor mile', viewAll: 'Sab Dekho', viewDetails: 'Details Dekho',
    bookAppointment: 'Appointment Lo', registerNow: 'Register Karo', availableToday: 'Aaj Available',
    bedsAvailable: 'Bed Available', icuFree: 'ICU Khali', bedOccupancy: 'Bed Bharao',
    emergencyNumbers: 'Emergency Numbers', quickAccess: 'India bhar ki emergency services tak jaldi pahuncho',
    ambulance: 'Ambulance', police: 'Police', fire: 'Aag Brigade',
    topHospitals: 'Top Hospitals', topSpecialists: 'Best Doctors', ourSpecialties: 'Hamari Specialties',
    upcomingCamps: 'Aane Wale Health Camps', downloadApp: 'App Download Karo',
    choosePlan: 'Plan Choose Karo', currentPlan: 'Current Plan', subscribeNow: 'Subscribe Karo',
    loading: 'Load ho raha hai...', noResults: 'Kuch nahi mila', clearFilters: 'Filters Hatao',
    language: 'Bhasha', searchPlaceholder: 'Doctor, hospital ya bimari dhundo...',
    verifiedHospitals: 'Verified Hospitals', expertDoctors: 'Expert Doctors',
    happyPatients: 'Khush Patients', yearsService: 'Saal ki Service',
    needEmergencyHelp: 'Emergency Help Chahiye?', emergencyDesc: 'Hamari 24/7 emergency services hamesha ready hain.',
    findNearest: 'Najdiki Hospital Dhundo', campsFree: 'Aapke paas free health check camps',
    chatAssistant: 'Health Sahayak', chatOnline: 'Online • Help ke liye ready',
    chatPlaceholder: 'Apna message likho...', quickActions: 'Jaldi karo:',
    findNearestHospital: 'Najdiki hospital', bookAppointmentAction: 'Appointment lo',
    emergencyHelp: 'Emergency help', findSpecialist: 'Doctor dhundo',
    healthTips: 'Health tips', medicinesInfo: 'Dawai ki jankari',
    emergencyCallTitle: '🚨 Emergency Check',
    emergencyCallDesc: 'Aap kaafi der se browse kar rahe hain. Kya aapko emergency medical help chahiye?',
    yesEmergency: 'Haan, help chahiye!', noEmergency: 'Nahi, main theek hoon',
    connectingHospital: 'Sajdiki hospital se connect kar rahe hain...',
    aiSpeaking: 'AI Sahayak bol raha hai...',
  },
};

interface LanguageContextType {
  lang: string;
  setLang: (l: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en', setLang: () => {}, t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState('en');

  // Load from localStorage and set html lang
  useEffect(() => {
    const stored = localStorage.getItem('app_lang');
    if (stored) setLang(stored);
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const handleSetLang = (newLang: string) => {
    setLang(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key: string) => translations[lang]?.[key] || translations.en?.[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
export const availableLanguages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'hinglish', name: 'Hinglish', flag: '🇮🇳' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
  { code: 'ta', name: 'தமிழ்', flag: '🇱🇰' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
];
